### PR TITLE
Accept a context in the open method.

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/17)

### CODE REVIEW

**Comment by Saulis** [comment]
Here's a different take on this: what if we just removed `open()`, `close()` and `opened` from the public API? Is there a use case for having them or are they just for "convenience" ?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-:-KSAOa_fcGMpDNDJw0Hx:b-bogolh)*

**Comment by tomivirkki** [comment]
*[vaadin-context-menu.html, line 158 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-KSAQ_j1TMcuq-PMGGn8:-KSAQ_j1TMcuq-PMGGn9:b-e4jzmm) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b91c45b8c3aaa944642ad8de32a90da61c75d4c/vaadin-context-menu.html#L158)):*
> ```HTML
>        *    out the position of the menu.
>        */
>       open: function(ev) {
> ```

Passing an event as parameter just for figuring out x and y isn't clean for public API. Rather `open(x, y)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17)*

**Comment by manolo** [comment]
From the developer point of view, imperative could be easier in some circumstances. For instance the developer could have multiple context menus, and he open one or another depending on the element or event type etc. I'm thinking on having a context menu for the header with multi enabled, a context for a certain row for setting some value etc.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[vaadin-context-menu.html, line 158 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-KSAQ_j1TMcuq-PMGGn8:-KSDxU0lL2-ln3e_HfBA:b-wb85v4) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b91c45b8c3aaa944642ad8de32a90da61c75d4c/vaadin-context-menu.html#L158)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Passing an event as parameter just for figuring out x and y isn't clean for public API. Rather `open(x, y)`
</details>
Not only for x & y but also is used for setting the context: detail, target, etc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-:-KSDxf9K7s-NmzO2OluD:b-aibpjd)*

**Comment by manolo** [comment]
The idea behind this is that we have a declarative way to open and define the context at the same time, I can call the _onContextMenu(ev) instead but it's a private API.
From the developer point of view, It should be a way to open the menu programatically, I think the most standard method is open.
Here you have  a code example

```
           <vaadin-grid id="grid" items="[[_items()]]"
               detailed-events='["click"]' on-detailed-click="_open">
              <table>
                <colgroup>
                  <col name="name" >
                  <col name="surname">
                  <col name="activity">
                  <col name="target">
                  <col name="effort">
                </colgroup>
              </table>
            </vaadin-grid>
            <vaadin-context-menu id="headermenu">
              <template>
                <paper-menu multi >
                  <paper-item>Name</paper-item>
                  <paper-item>Surname</paper-item>
                  <paper-item>Activity</paper-item>
                  <paper-item>Target</paper-item>
                </paper-menu>
              </template>
            </vaadin-context-menu>
            <vaadin-context-menu id="effortmenu">
              <template>
                <paper-menu>
                  <paper-item>1</paper-item>
                  <paper-item>2</paper-item>
                  <paper-item>3</paper-item>
                  <paper-item>4</paper-item>
                  <paper-item>5</paper-item>
                </paper-menu>
              </template>
            </vaadin-context-menu>
```

```
        _open: function(ev) {
            ev.preventDefault();
            if (ev.detail.section == 'header') {
              this.$.headermenu.open(ev);
            } else if (ev.detail.section == 'body' && ev.detail.column == 4) {
              this.$.effortmenu.open(ev);
            }
          }
```

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-:-KSFbbg13-tkPXl6VHE9:b-1x3kk8)*

**Comment by manolo** [comment]
Note that reusing the same context menu is not an option here because each would have different behaviour (multiple selection, not close on click, etc)

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-:-KSFi4ujfMx_tXjyPMUa:b-v0jopa)*

**Comment by Saulis** [comment]
Hmm.. but you still have at least two ways of achieving this without calling `open()`

Either by firing two different events for header and body (in the case when you have control over the component)
or using one context menu which changes contents based on the `detail` properties. 

It's a matter of taste which approach is cleanest or easiest, point being that the use case can be fulfilled without having `open()` in the public API. That makes the `open()` a convenience method at most. 

I'm not against convenience methods per-se, but in this case having `open()` leads into a rabbit hole discussion regarding the arguments (i.e. `event` vs. `x, y`) which I would gladly postpone until an actual user comes to us with a feature request.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-:-KSFuWnSrcaQm5JnWz0L:b-mi9uwj)*

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[vaadin-context-menu.html, line 213 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-KSFvxyQkUug38xhmAhV:-KSFvxyQkUug38xhmAhW:bcu7l7i) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b91c45b8c3aaa944642ad8de32a90da61c75d4c/vaadin-context-menu.html#L213)):*
> ```HTML
> 
>         if (this._context.target) {
>           var ev = e.detail && e.detail.event || e.detail || e;
> ```

`ev` is an event or a detail or an event? This is really confusing.

Also, the `ev` name doesn’t tell any difference from `e`, which is also an event.

---

*[vaadin-context-menu.html, line 215 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-KSFwAaHth1UeCjOones:-KSFwAaHth1UeCjOonet:b-r3spi2) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b91c45b8c3aaa944642ad8de32a90da61c75d4c/vaadin-context-menu.html#L215)):*
> ```HTML
>           var ev = e.detail && e.detail.event || e.detail || e;
> 
>           (ev.preventDefault || e.preventDefault)();
> ```

Since the detailed events are preventable themselves, there’s no need of original event lookup and prevention.

We can just leave `e.preventDefault()` as it was before here.

---

*[vaadin-context-menu.html, line 219 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-KSFwVmuPZZod7W9pMWM:-KSFwVmuPZZod7W9pMWN:btcgmyp) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b91c45b8c3aaa944642ad8de32a90da61c75d4c/vaadin-context-menu.html#L219)):*
> ```HTML
> 
>           this.$.overlay.resetFit();
>           this.$.overlay.x = ev.clientX;
> ```

I’d like to see a less obscure logic here. Say, explicit:

```javascript
this.$.overlay.x = originalEvent && originalEvent.clientX ||
    event.detail && event.detail.clientX ||
    event.clientX
```

More verbose, but easier to understand.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17)*

**Comment by manolo** [comment]
> Either by firing two different events for header and body (in the case when you have control over the component)
> or using one context menu which changes contents based on the detail properties.

That is not an option, the component is a closed shadow box which only gives info about the original event after it fires the detailed event. Can you post here a code without modifying the 3rd party component (this case grid-1 with the detailed patch)

> (i.e. event vs. x, y)

The documented context API of the vaadin-context-menu demands an event. I want to use that API declaratively, I not only need x and y but the details, so event as argument makes absolutly sense to me, unless there is a public way to set the context and call the _onContextMenu

Another option is if we have a method for setting the context like `mymenu.context = {...}; mymenu.open = true` but I think it is more complex.

 > I would gladly postpone until an actual user comes to us with a feature request.

Consider this as my own feature request :-).
This PR is the result of my personal dog-fooding. Otherwise, I cannot have different menus based on the grid sections/columns info interacting with grid and data.

---

Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-context-menu.html, line 213 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-KSFvxyQkUug38xhmAhV:-KSGKfeB95ZvdEWFWD2N:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b91c45b8c3aaa944642ad8de32a90da61c75d4c/vaadin-context-menu.html#L213)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> `ev` is an event or a detail or an event? This is really confusing.
> 
> Also, the `ev` name doesn’t tell any difference from `e`, which is also an event.
</details>
Done.

---

*[vaadin-context-menu.html, line 215 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-KSFwAaHth1UeCjOones:-KSGAQyB2R3WSHxfu7xM:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b91c45b8c3aaa944642ad8de32a90da61c75d4c/vaadin-context-menu.html#L215)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Since the detailed events are preventable themselves, there’s no need of original event lookup and prevention.
> 
> We can just leave `e.preventDefault()` as it was before here.
</details>
Done.

---

*[vaadin-context-menu.html, line 219 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-KSFwVmuPZZod7W9pMWM:-KSGKlA3zoV5Z1hATX88:b-6tjmqy) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b91c45b8c3aaa944642ad8de32a90da61c75d4c/vaadin-context-menu.html#L219)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> I’d like to see a less obscure logic here. Say, explicit:
> 
> ```javascript
> this.$.overlay.x = originalEvent && originalEvent.clientX ||
>     event.detail && event.detail.clientX ||
>     event.clientX
> ```
> 
> More verbose, but easier to understand.
</details>
I do prefer smaller js sizes, but changed to make it more understandable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-:-KSGAvBQY-gifK7kkyfM:bwj512a)*

**Comment by platosha** [comment]
The idea is good to me, in general :thumbsup:

I would not be in a hurry with merging this, though. Plenty of things to think of. For instance, #13 could affect this PR as well: we’re considering changing the opening mode (fullscreen or regular) depending on the incoming event type.

Please don’t forget to add tests and demos, if the team would give it a go.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-context-menu.html, line 209 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-KSH7iptvBQ67_iOj5Tx:-KSH7iptvBQ67_iOj5Ty:bqde4yo) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/eee33011ff97785645b27d97d443366739bc18fc/vaadin-context-menu.html#L209)):*
> ```HTML
>       _onContextMenu: function(event) {
>         event.preventDefault();
>         event.stopPropagation();
> ```

Note that the opening is under a condition. Only opens when the target is present.

Previously, the event was prevented only if the menu is opened by this listener, meaning that the event was handled. Now we prevent any of the events received. What is the reason behind this change?

If the target is absent, and the context menu refuses to open, we should not prevent the event, but rather just do nothing and pass the event further. There might be another instance of `<vaadin-context-menu>` listening for this event on the same node, but targeted differently from the current one. It this case, the other instance should receive and prevent the event.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-:-KSH9ORCdcjLEwHPGqW_:blg4ago)*

**Comment by manolo** [comment]
will work on tests

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-context-menu.html, line 209 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-KSH7iptvBQ67_iOj5Tx:-KSHBoaWBNuEI0j_sS5s:b-lnf44k) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/eee33011ff97785645b27d97d443366739bc18fc/vaadin-context-menu.html#L209)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Note that the opening is under a condition. Only opens when the target is present.
> 
> Previously, the event was prevented only if the menu is opened by this listener, meaning that the event was handled. Now we prevent any of the events received. What is the reason behind this change?
> 
> If the target is absent, and the context menu refuses to open, we should not prevent the event, but rather just do nothing and pass the event further. There might be another instance of `<vaadin-context-menu>` listening for this event on the same node, but targeted differently from the current one. It this case, the other instance should receive and prevent the event.
</details>
No reason, wrong copy and paste. Moved to its original place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-:-KSHCJS5XIbN6S-3DBCJ:b-5ziwqi)*

**Comment by manolo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-context-menu.html, line 209 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-KSH7iptvBQ67_iOj5Tx:-KSK_5Sd-ZGd9PeLzpkL:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/eee33011ff97785645b27d97d443366739bc18fc/vaadin-context-menu.html#L209)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> No reason, wrong copy and paste. Moved to its original place.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17)*

**Comment by Saulis** [comment]
You can do either with one menu:

```html
<vaadin-context-menu open-on="custom-event">
  <template>
    <template is="dom-if" if="[[_isHeader(detail)]]">
      <paper-menu>..</paper-menu>
    </template>
    <template is="dom-if" if="[[!_isHeader(detail)]]">
      <paper-menu>..</paper-menu>
    </template>
  </template>
</vaadin-context-menu>
<script>
 _isHeader: function(detail) {
   return detail.section === 'header';
 }
</script>
```

or if you want to have two menus:

```js
 _onCustomEvent: function(e) {
  if (e.detail.section === 'header') {
   this.$.headerMenu.fire('contextmenu', e);
 } else {
  this.$.bodyMenu.fire('contextmenu', e);
}
};
```

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-:-KSKbWDBWarJeyXA64EV:b4v81tk)*

**Comment by manolo** [comment]
An API that needs firing an event for opening an overlay sounds very confusing to my DX.  Almost popups do it using an open method. Also no API for setting the context object used in the template but firing the event is highly confusing.

If we want an API based on events to handle the menu imperatively we need to document it correctly. Otherwise having convenience methods sounds more maintainable to me. 

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-:-KSKm0KR0gdM9LprEcfv:b-hs1x57)*

**Comment by manolo** [comment]
@saulis the first approach opens the menu in position 0x0 because custom-event does not have info about the clientX/Y that is the reason in this patch of the considering the originalEvent = e.detail.event 
The second approach does the position ok doing `this.$.headerMenu.fire('contextmenu', e.detail.event);` but other info in detail is missing.

So if we don't go with `open(event)` at least need that a synthetic event could bring the original event in the detail.

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-:-KSKtMgE-6W6Y-hsQKQm:bi740f1)*

**Comment by Saulis** [comment]
The custom event feature is designed so that user should always provide `clientX` and `clientY` in the `detail` object. That should be documented better.

As said, I agree that having `open()` is more convenient. There's just some undecided issues regarding it like the method arguments (event vs. x,y, detail etc) and what should we do with the `opened` property. 

To me personally it feels a better use of our time to just remove them all and skip all that debate. Keeping in mind using custom event from inside a shadow DOM together with multiple context menus is a really advanced use case. And as I've demonstrated, it can be done without `open()`

Now, I don't have strong opinion on this and I'm ok with ever way we decide to go, but I'd be happy to hear some more opinions from people. ping @samiheikki @platosha @tomivirkki @tehapo 

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-:-KSL6ow3C0wDMNA2pndE:bnlpt83)*

**Comment by manolo** [comment]
I don't want to make you waste your time nor mine, since I can use the private API for my porpoises, closing this.

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-:-KSLJDU53VtFjPw1s5k3:b-jp0y6g)*

**Comment by Saulis** [comment]
We discussed with @platosha  and @tomivirkki and this is our proposal, basically making `opened` private and forcing `open()` to always have the event as an argument. Please have a look.

---

Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-:-KSM3Rf2pn6d0NYA6X8A:b-ej29m7)*

**Comment by manolo** [comment]
There are a couple of questions:
1.- Is it ok that we don't support the opened attribute anymore?. Almost popup widgets in polymer have it (toast, dialog, vaadin-combo). We could consider that context-menu does not have use cases where the user want's it opened. That is the case of paper-tooltip that does not have the opened attribute.

2.- In my PR I had the option of passing the original event as part of the detail, so the position was taken from it. 
For me makes sense to have a convention where components could pass an original event in the `details.event` property, the attribute name could be arguable, but the original event could be very useful, specially to components wanting to inspect certain things like key modifiers, touch info etc.
Another option is that the widget passes the original event as the details. It's doable, but  maybe confusing.
If we don't go with the `ev.details.event` solution but `ev.details` then the grid PR should be modified. Both solutions work to me.

---

Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-:-KS_Ft-xpDcdOVdjI8u4:bj0iaqu)*

**Comment by Saulis** [comment]
1) Having `opened` public implies having some properties that user can use to at least define the position of the overlay. Probably also properties for target and details. Other components like the ones you mentioned don't change position or other properties on each opening so it works simpler. I would advise that we try to keep the API to a minimum at this point at least, and re-evaluate the need for `opened` & co closer to `1.0` when everything is more stable.

2) Yeah, we we're thinking on passing the original event as `ev.details` for custom events when needed. In this case there only one place where the `clientX` and `clientY` properties are used from.

---

Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-:-KS_ija3gsThBoNEJzpD:b-3umooe)*

**Comment by manolo** [comment]
Review status: 1 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-context-menu.html, line 212 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-KSaSNlQaP-iJ9l1BWJh:-KSaSNlQaP-iJ9l1BWJi:b3l5s2c) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b9acd61ae4fb1bbe364cf595aff92f2b6fb3723d/vaadin-context-menu.html#L212)):*
> ```HTML
>             var detailEvent = e.detail && e.detail.originalEvent || e;
>             this.$.overlay.x = detailEvent.clientX;
>             this.$.overlay.y = detailEvent.clientY;
> ```

I would check whether clientX/Y exists in originalEvent, then in e.detail and finally in e, see code in r2

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17)*

**Comment by manolo** [comment]
Review status: 1 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-context-menu.html, line 212 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-KSaSNlQaP-iJ9l1BWJh:-KSaTx1wA1bFU_qCezBB:b-gg0d3a) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b9acd61ae4fb1bbe364cf595aff92f2b6fb3723d/vaadin-context-menu.html#L212)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I would check whether clientX/Y exists in originalEvent, then in e.detail and finally in e, see code in r2
</details>
Well, unless we don't support clientX/Y  coming in the detail `ev.detail.clientX`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17)*

**Comment by Saulis** [comment]
Review status: 1 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-context-menu.html, line 212 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-KSaSNlQaP-iJ9l1BWJh:-KSaVqlxYavM-Nfc4mUA:bh1kwdc) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b9acd61ae4fb1bbe364cf595aff92f2b6fb3723d/vaadin-context-menu.html#L212)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Well, unless we don't support clientX/Y  coming in the detail `ev.detail.clientX`
</details>
Yeah we decided to leave `ev.detail.clientX` out for now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17)*

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r1, 5 of 7 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-context-menu.html, line 212 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-KSaSNlQaP-iJ9l1BWJh:-KSaYYF2AaTTP-Eeeykl:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b9acd61ae4fb1bbe364cf595aff92f2b6fb3723d/vaadin-context-menu.html#L212)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Yeah we decided to leave `ev.detail.clientX` out for now
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/17#-:-KSaer9EbA5047bXT3Q9:bnfp4nl)*

**Pull request merged**
