### PR TITLE
Detect phones based on touch support and device width

### LINKED ISSUE #13: Improve “fullscreen mode” detection
Currently we only rely on viewport size for triggering the “fullscreen” mode of the overlay. This ends up being a bit strange on desktop/mouse devices, when there is still plenty of viewport estate to show the overlay next to the mouse cursor.

One option is to adjust the mode based on the originating event, was the overlay triggered with a mouse or with touch.

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #13

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/22)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[demo/index.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-KSk1dwTwqZuls-5jJSJ:-KSk1dwTwqZuls-5jJSK:b-xf2qtw) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/957c29f663bb64cb3639faea5dd07022079e3a42/demo/index.html#L36)):*
> ```HTML
>       <template>
>         <template is="dom-bind" id="container">
>           <vaadin-context-menu selector="a" open-on="tap">
> ```

This makes the popup be misplaced on iPad but it's a separate bug I guess (not a regression form this PR)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22)*

**Comment by Saulis** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-device-detector.html, line 49 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-KSfHguS1xor7vItfs26:-KSoS-GFGP2KSYLpIL1X:b-eljm0p) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/bd8254db31f3525a64598134a3d24e598c712424/vaadin-device-detector.html#L49)):*
<details><summary><i>Previously, tehapo (Teemu Pöntelin) wrote…</i></summary>
> I guess this might be incorrect in case of a touch screen enabled laptop?
</details>
Yeah... although it's not all that clear if a touch screen laptop is just a tablet with a keyboard :-)

---

*[demo/index.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-KSk1dwTwqZuls-5jJSJ:-KSoSDce-OGnh_1GU-lI:bs3qhts) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/957c29f663bb64cb3639faea5dd07022079e3a42/demo/index.html#L36)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> This makes the popup be misplaced on iPad but it's a separate bug I guess (not a regression form this PR)?
</details>
Yeah the `open-on` was accidentally added in some previous commit (by yours truly)

---

*[test/device-detector.html, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-KSfHWW2r3pJ0E3V1rMd:-KSoSbBOpKswO-Sbczbw:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/bd8254db31f3525a64598134a3d24e598c712424/test/device-detector.html#L12)):*
<details><summary><i>Previously, tehapo (Teemu Pöntelin) wrote…</i></summary>
> MockInteractions is never used but still imported.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22)*

**Comment by tehapo** [comment]
One more question that came to my mind is that should we take device orientation (portrait/landscape) into account? Otherwise LGTM.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-:-KSoaoPGeFnHqKVwzR9o:b-wpoji5)*

**Comment by tomivirkki** [comment]
*[demo/index.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-KSk1dwTwqZuls-5jJSJ:-KSpOADVF6ifMx_NQ_LJ:b-qhf6kq) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/957c29f663bb64cb3639faea5dd07022079e3a42/demo/index.html#L36)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Yeah the `open-on` was accidentally added in some previous commit (by yours truly)
</details>
I meant that the popup gets misplaced after removing this binding. Need a fix for the original issue (but not in this PR).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-device-detector.html, line 5 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-KSopRfsEMeNSzL4BhiI:-KSopRfsEMeNSzL4BhiJ:bymd83z) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/9b5183cc57eb1def835a89e8c84a072fe0262a02/vaadin-device-detector.html#L5)):*
> ```HTML
> <dom-module id="vaadin-device-detector">
>   <template>
>     <iron-media-query query="min-device-width: 750px" query-matches="{{wide}}"></iron-media-query>
> ```

I think 750 should be configurable by user utilising this element

---

*[vaadin-device-detector.html, line 24 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-KSoqBufN04v5eAya7hq:-KSoqBufN04v5eAya7hr:bnojoo9) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/9b5183cc57eb1def835a89e8c84a072fe0262a02/vaadin-device-detector.html#L24)):*
> ```HTML
>         },
> 
>         tablet: {
> ```

tablet seems not be used. It's logic to remove it until it's actually needed

---

*[vaadin-device-detector.html, line 57 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-KSopc3oahiNg1vK82Ti:-KSopc3oahiNg1vK82Tj:b-rcwkf2) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/9b5183cc57eb1def835a89e8c84a072fe0262a02/vaadin-device-detector.html#L57)):*
> ```HTML
> 
>       _tablet: function(wide, touch) {
>         return wide && touch;
> ```

 PC's with touch screens are considered tablets ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-device-detector.html, line 5 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-KSopRfsEMeNSzL4BhiI:-KT8NINdU8t4D3ua_0FW:bb6uyes) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/9b5183cc57eb1def835a89e8c84a072fe0262a02/vaadin-device-detector.html#L5)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I think 750 should be configurable by user utilising this element
</details>
Are you also suggesting to propagate that property out from `vaadin-context-menu` ? I would postpone doing that until someone sends a request.

---

*[vaadin-device-detector.html, line 24 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-KSoqBufN04v5eAya7hq:-KT8MCIW-lgUH3JrZ-KT:b-1of6qb) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/9b5183cc57eb1def835a89e8c84a072fe0262a02/vaadin-device-detector.html#L24)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> tablet seems not be used. It's logic to remove it until it's actually needed
</details>
OK.. I guess `desktop` should be removed also?

---

*[vaadin-device-detector.html, line 57 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-KSopc3oahiNg1vK82Ti:-KT8MMbhvlw3aRtH01_U:b-6ukkf2) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/9b5183cc57eb1def835a89e8c84a072fe0262a02/vaadin-device-detector.html#L57)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
>  PC's with touch screens are considered tablets ? 
</details>
Well.. currently yes. It's tricky to draw the line between desktop/tablet for devices like MS Surface which is tablet and a fullblown PC at the same time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22)*

**Comment by platosha** [comment]
What happens when a user opens a context menu with a right mouse click inside a narrow browser window on a touch-enabled laptop?

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-:-KT9jvdLxdxEd6OFT-tc:b-sqc1r2)*

**Comment by Saulis** [comment]
We use `device-min-width` which is not affected when browser window size changes. So, the touch-enabled laptop should behave as "tablet" all the time.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-:-KTDX97GRKKj-t9GSO2z:bfv7yez)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-device-detector.html, line 5 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-KSopRfsEMeNSzL4BhiI:-KTIR5lrvtfn8nSJDdN_:b-sh8bkh) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/9b5183cc57eb1def835a89e8c84a072fe0262a02/vaadin-device-detector.html#L5)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Are you also suggesting to propagate that property out from `vaadin-context-menu` ? I would postpone doing that until someone sends a request.
</details>
sounds good to postpone

---

*[vaadin-device-detector.html, line 24 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-KSoqBufN04v5eAya7hq:-KTNXIuUYm_e15MHLZ3I:b2nhswy) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/9b5183cc57eb1def835a89e8c84a072fe0262a02/vaadin-device-detector.html#L24)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> OK.. I guess `desktop` should be removed also?
</details>
Yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22)*

**Comment by Saulis** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-device-detector.html, line 24 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-KSoqBufN04v5eAya7hq:-KTTo6gTUMm65HQJXux_:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/9b5183cc57eb1def835a89e8c84a072fe0262a02/vaadin-device-detector.html#L24)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Yes
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-:-KTm992Z94DTmKWrRWMq:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/22#-:-KTmHdx8vo1S-06FysF3:bnfp4nl)*

**Pull request merged**
