### PR TITLE
Use extracted vaadin-overlay

### LINKED ISSUE #80: Switch to using vaadin-overlay

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #80

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/85)

### CODE REVIEW

**Comment by limonte** [comment]
Nicely done! The first regression I noticed: https://github.com/vaadin/vaadin-context-menu/issues/65

**Comment by tomivirkki** [comment]
*[vaadin-context-menu.html, line 24 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85#-KnhevSEbK0Iw79L3N3H:-KnhevSEbK0Iw79L3N3I:b-iexu3d) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/1ba9d507e7c80f5bd429291ded88cffdfa119c60/vaadin-context-menu.html#L24)):*
> ```HTML
> 
>       /* TODO: replace with [part="backdrop"] https://github.com/vaadin/vaadin-overlay/issues/1 */
>       :host(.vaadin-context-menu-overlay:not([phone]))::before {
> ```

This override wouldn't be needed if the `withBackdrop` property was conditional also:
`with-backdrop="[[_phone]]"`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85)*

**Comment by Saulis** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-context-menu.html, line 24 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85#-KnhevSEbK0Iw79L3N3H:-KnnfUGirPe1RtPvARiX:b-227nn8) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/1ba9d507e7c80f5bd429291ded88cffdfa119c60/vaadin-context-menu.html#L24)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This override wouldn't be needed if the `withBackdrop` property was conditional also:
`with-backdrop="[[_phone]]"`
</blockquote></details>

I enabled the backdrop always with context-menu (transparent on desktop) so that we can use it to catch additional contextmenu clicks which should close the overlay. I guess we could alternatively add a `contextmenu` listener on the body using capture mode (same approach as with the outside click listener), but though this approach would be cleaner?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85)*

**Comment by manolo** [comment]
Review status: 0 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-context-menu.html, line 24 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85#-KnhevSEbK0Iw79L3N3H:-KnrpRtNwm4nQhpj34YB:bmb17o2) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/1ba9d507e7c80f5bd429291ded88cffdfa119c60/vaadin-context-menu.html#L24)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I enabled the backdrop always with context-menu (transparent on desktop) so that we can use it to catch additional contextmenu clicks which should close the overlay. I guess we could alternatively add a `contextmenu` listener on the body using capture mode (same approach as with the outside click listener), but though this approach would be cleaner?
</blockquote></details>

backdrop click seems cleaner if nothing else could cover it

---

*[vaadin-context-menu.html, line 59 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85#-KnrrDnSAk7QVA2dGmkZ:-KnrrDnSAk7QVA2dGmk_:bwky875) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/1ba9d507e7c80f5bd429291ded88cffdfa119c60/vaadin-context-menu.html#L59)):*
> ```HTML
>     <slot id="slot"></slot>
> 
>     <vaadin-device-detector phone="{{_phone}}"></vaadin-device-detector>
> ```

I think device-detector could be useful for other elements, so it might be a helper element in the vaadin-overlay repo.
No blocking for this PR, it can be done after it.

---

*[vaadin-context-menu.html, line 322 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85#-KnrrY7fLEl3t8Us6cOm:-KnrrY7fLEl3t8Us6cOn:btlhq64) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/1ba9d507e7c80f5bd429291ded88cffdfa119c60/vaadin-context-menu.html#L322)):*
> ```HTML
> 
>         _closeOnChanged(closeOn, oldCloseOn) {
>            // Listen on this.$.overlay.root to workaround issue on
> ```

Nit: extra space

---

*[vaadin-context-menu.html, line 413 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85#-Knrshhc_v6_xMM09CfT:-Knrshhc_v6_xMM09CfU:b-999l4a) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/1ba9d507e7c80f5bd429291ded88cffdfa119c60/vaadin-context-menu.html#L413)):*
> ```HTML
> 
>               // FIXME: Nasty hack
>               requestAnimationFrame(() => {
> ```

Why requestAnimationFrame instead of microtask for instance?

---

*[test/overlay.html, line 35 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85#-KnrssQ65-fdjuWzNOBY:-KnrssQ65-fdjuWzNOBZ:b9waj3n) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/1ba9d507e7c80f5bd429291ded88cffdfa119c60/test/overlay.html#L35)):*
> ```HTML
> 
>         afterEach(() => {
>           menu.$.overlay.opened = false;
> ```

could be in one line, the same with beforeEach

---

*[test/touch.html, line 150 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85#-Knrt7ulLflhYVlsu7f4:-Knrt7ulLflhYVlsu7f5:b2gjoz7) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/1ba9d507e7c80f5bd429291ded88cffdfa119c60/test/touch.html#L150)):*
> ```HTML
>           makeSoloTouchEvent('touchstart', xy, target);
> 
>           listenOnce(menu, 'opened-changed', () => {
> ```

you can remove all brackets blocks and inline in the arrow

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r3, 3 of 9 files at r4, 2 of 5 files at r7, 1 of 3 files at r9, 3 of 3 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 1 of 4 files at r14.
Review status: 8 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-context-menu.html, line 24 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85#-KnhevSEbK0Iw79L3N3H:-KqY0zTdDeRVANwXyh95:bfdgatn) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/1ba9d507e7c80f5bd429291ded88cffdfa119c60/vaadin-context-menu.html#L24)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

backdrop click seems cleaner if nothing else could cover it
</blockquote></details>

Removed the TODO and adjusted CSS parts.
Also added background transparent to backdrop in desktop.
I agree that backdrop facilitates things.

---

*[vaadin-context-menu.html, line 322 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85#-KnrrY7fLEl3t8Us6cOm:-KqY1NP8MWkuQa2lKP1H:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/1ba9d507e7c80f5bd429291ded88cffdfa119c60/vaadin-context-menu.html#L322)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Nit: extra space
</blockquote></details>

Done

---

*[test/overlay.html, line 35 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85#-KnrssQ65-fdjuWzNOBY:-KqY1kqtb-kNx5e9WkHH:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/1ba9d507e7c80f5bd429291ded88cffdfa119c60/test/overlay.html#L35)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

could be in one line, the same with beforeEach
</blockquote></details>

Done

---

*[test/touch.html, line 150 at r10](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85#-Knrt7ulLflhYVlsu7f4:-KqY22zFWLO-Oy6fYWmr:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/1ba9d507e7c80f5bd429291ded88cffdfa119c60/test/touch.html#L150)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

you can remove all brackets blocks and inline in the arrow
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85#-:-KqYP-aNYSmMqQx2Gilx:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 1 of 5 files at r13, 3 of 4 files at r14.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85)*

**Comment by samiheikki** [comment]
Reviewed 1 of 3 files at r3, 3 of 9 files at r4, 1 of 5 files at r7, 1 of 3 files at r9, 1 of 3 files at r10, 1 of 5 files at r13, 4 of 4 files at r14.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-context-menu.html, line 356 at r14](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85#-KqboIn93fUmyt8OLXpn:-KqboIn93fUmyt8OLXpo:bfj9f02) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b00633138777ec53e72982bb38b0730b2928f03/vaadin-context-menu.html#L356)):*
> ```HTML
>           }
> 
>           // TODO @Sauli: file issue for polymer-effects.html:571
> ```

Guess this should be done and comment removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/85)*

**Pull request merged**
