### PR TITLE
Use vaadin-list-box in demos as default

### PR DESCRIPTION
**Pull request by manolo**
vaadin-list-box and vaadin-item should be the normal way to create context menus.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/122)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/context-menu-basic-demos.html, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/122#-Kzo7bq3UADrGUDtUBBj:-Kzo7bq3UADrGUDtUBBk:bwsamtn) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/393dd9d816e698d9a5b9e25830cd45ea49b1014b/demo/context-menu-basic-demos.html#L15)):*
> ```HTML
>         <vaadin-context-menu>
>           <template>
>             <vaadin-list-box>
> ```

nit: you can now remove "With Vaadin List Box" demo added by me in my previous PR

---

*[demo/context-menu-integration-demos.html, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/122#-Kzo7y8sEm7hRkdaKSjQ:-Kzo7y8sEm7hRkdaKSjR:bf2c7q2) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/393dd9d816e698d9a5b9e25830cd45ea49b1014b/demo/context-menu-integration-demos.html#L9)):*
> ```HTML
>     </style>
> 
>     <h3>Vaadin list Box</h3>
> ```

nit: capitalize "list" - "List" for consistency

---

*[demo/context-menu-integration-demos.html, line 44 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/122#-Kzo7t4jqx5RnbZa1lJl:-Kzo7t4jqx5RnbZa1lJm:b-v1i5s1) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/393dd9d816e698d9a5b9e25830cd45ea49b1014b/demo/context-menu-integration-demos.html#L44)):*
> ```HTML
> 
>     <h3>Paper Listbox</h3>
>     <vaadin-demo-snippet id='context-menu-basic-demos-basic-usage'>
> ```

nit: rename this `id`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/122)*

**Comment by manolo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/context-menu-basic-demos.html, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/122#-Kzo7bq3UADrGUDtUBBj:-Kzy5G453__Z_Je858U5:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/393dd9d816e698d9a5b9e25830cd45ea49b1014b/demo/context-menu-basic-demos.html#L15)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: you can now remove "With Vaadin List Box" demo added by me in my previous PR
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/122)*

**Comment by manolo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/context-menu-integration-demos.html, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/122#-Kzo7y8sEm7hRkdaKSjQ:-Kzy5dlk5Gix0vZq0Spr:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/393dd9d816e698d9a5b9e25830cd45ea49b1014b/demo/context-menu-integration-demos.html#L9)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: capitalize "list" - "List" for consistency
</blockquote></details>

Done.

---

*[demo/context-menu-integration-demos.html, line 44 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/122#-Kzo7t4jqx5RnbZa1lJl:-Kzy5e7wcdbf_iz69izF:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/393dd9d816e698d9a5b9e25830cd45ea49b1014b/demo/context-menu-integration-demos.html#L44)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: rename this `id`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/122)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/122#-:-Kzy6CiCN64qTTHaA8DB:bnfp4nl)*

**Pull request merged**
