### PR TITLE
Added support for keyboard control of menu item

### LINKED ISSUE #279: Support for anchor by keyboard control
If you add a link to a MenuItem it can not be accessed by keyboard.
This is supported in a [tab](https://github.com/vaadin/vaadin-tabs/blob/87d98e1d4cfd3f5a4dc28666b8ae650443219298/src/vaadin-tab.html#L63-L74), but not in a MenuItem.

### PR DESCRIPTION
**Pull request by xmicore**
This pull request resolves #279.

### CODE REVIEW

**Comment by xmicore** [comment]
An anchor in a menu item could not be controlled via the keyboard. A simple link in the menu is a bigger issue.

**Comment by xmicore** [comment]
#277

**Comment by xmicore** [comment]
I have opened the issue #279 .

**Comment by web-padawan** [comment]
Sorry about the delay, our team has quite limited capacity at the moment.

In the meanwhile, I created a workaround that can be added to the project to monkey patch `vaadin-item` :see_no_evil: 

```js
const ItemElement = customElements.get('vaadin-item');

if (ItemElement) {
  // store the original method
  const onKeyUp = ItemElement.prototype._onKeyup;

  ItemElement.prototype._onKeyup = function(event) {
    const item = Array.from(event.composedPath()).filter(el => el instanceof ItemElement)[0];
    const willClick = item.hasAttribute('active');

    // call the original method
    onKeyUp.call(item, event);

    if (willClick) {
      const anchor = item.querySelector('a');
      if (anchor) {
        anchor.click();
      }
    }
  };
}
```

**Comment by rolfsmeds** [comment]
This would need a unit test -- see the corresponding unit test for Tabs for inspiration: https://github.com/vaadin/vaadin-tabs/commit/b657fa235d86590fc39d690d5a6e848b9a8b7e97#diff-6fcdd3aebeb3be69481f063aaed32b8017c4a4a588cd01223e26ddb8d9a03da9

**Comment by web-padawan** [comment]
It has been a while since this PR was submitted. Apologies about keeping it open for so long without any progress.
Please note, the new development for Vaadin web components will happen in the [monorepo](https://github.com/vaadin/vaadin-web-components).

I'm closing this now. We will submit a new PR to the monorepo when the linked issue is prioritised.

**Pull request closed without merging**
