### PR TITLE
Fix position of overlay in mobile, and scroll for long content, fixes #33

### LINKED ISSUE #33: Context-menu is misplaced when url bar appears/disappears
Reproducible with (at least) iOS Safari and Chrome. Found the issue in UX testing #19

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/37)

### CODE REVIEW

**Comment by samiheikki** [comment]
Almost working, but not quite. If I first open the context menu, it is working fine. But if I turn my phone to landscape mode and back to portrait the context-menu is misplaced and the bottom of context-menu is hidden.

1st open context-menu
img_4186

2nd turn phone to landscape mode
img_4187


3rd turn phone back to portrait
img_4188

**Comment by manolo** [comment]
That seems an issue unrelated with this PR. I cannot reproduce though.

What I have seen is that the issue is if we scroll in the overlay, figuring out a fix for it.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-:-KXp2bz7jFHDOYnpmci7:bxbdrfz)*

**Comment by samiheikki** [comment]
But the original issue #33 (Context-menu is misplaced when url bar appears/disappears) is because of the window resize. So I see it to be coupled with this.

**Comment by manolo** [comment]
Well, the original issue is because the user makes the url appears/disappears when moving the scroll.
IMO when the overlay is open in mobile scrolling shouldn't do anything, so avoiding moving the scrolling prevents this issue to happen. Obviously if the url bar appears, there is a resize event, but it's not necessary to handle in this issue with this fix.

Anyway if you want the problem be solved with resize events instead, let me know.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-:-KXpriNrQfZf0nZwjmJI:b-iocaia)*

**Comment by tomivirkki** [comment]
You can still scroll the document by touchmoving on the content element (menu) and this will reproduce the issue.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-:-KXtCsAFD46Our89nyWh:b-o73msm)*

**Comment by manolo** [comment]
Yep, I had not committed the fix for this

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-:-KXtFgE61rIMecZK-Pc8:bnnm2xr)*

**Comment by Saulis** [comment]
I agree with Sami here, #33 isn't fixed unless switching between landscape/portrait mode works.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-:-KXtJCI3Bky-gH77A3Da:b5y6gp4)*

**Comment by manolo** [comment]
Well #33 says `Context-menu is misplaced when url bar appears/disappears` nothing related with switching direction. IMO that is another issue.

Anyway I cannot reproduce the switching problem  it in my iPad or in simulator. What iOS version are you using?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-:-KXtK7zE_fGOtxhao1_7:b-l800dw)*

**Comment by Saulis** [comment]
Switching direction is related since that changes the url bar size at least in iOS. The issue is only reproducable on phones, because they use different positioning from iPad and desktop. Happens both on iOS 9 and 10, not sure about Android.

Did some debugging and the reason for incorrect positioning is that `IronFitBehavior` sets (for some reason) different `max-height` style values for the overlay while window is being resized. I witnessed values changing between `154px` to `280px` to `381px` to `114px` just by switching orientation between portrait and landscape.

Setting `max-height: 100vh` to the `:host([phone])` selector fixes this. I would also add `overflow: auto` there to make sure overlay contents are reachable in the case then contents are higher than the viewport.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-:-KXtPBQt72LjaSSO3QOi:b-26zyt6)*

**Comment by Saulis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[vaadin-context-menu-overlay.html, line 29 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KXuV7cMLWFsQf2hw-F1:-KXuV7cMLWFsQf2hw-F2:b2a11bs) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/dcf0f6dd502aec0912610b113f22e6d996f2fac7/vaadin-context-menu-overlay.html#L29)):*
> ```HTML
> 
>       :host([phone]) {
>         /* width set to make it possible for the user make the contents fit whole screen */
> ```

Please don't remove this comment

---

*[vaadin-context-menu-overlay.html, line 30 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KXu_Br_RtkwiNJNyRBP:-KXu_Br_RtkwiNJNyRBQ:bs1or5x) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b94ae5f72b56cc3e2b964f59cec8ee01ef621bc/vaadin-context-menu-overlay.html#L30)):*
> ```HTML
>       :host([phone]) {
>         width: 100vw;
>         max-height: calc(100vh - 48px);
> ```

Seems like the address bar height is different at least in different iPhones (5/6) so we can't use `100vh - 48px` – `max-height: 80vh` seems to work best for all of them.

---

*[vaadin-context-menu-overlay.html, line 82 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KXuTsA9qu9v4f_waQye:-KXuTsA9qu9v4f_waQyf:bvx0vhb) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b94ae5f72b56cc3e2b964f59cec8ee01ef621bc/vaadin-context-menu-overlay.html#L82)):*
> ```HTML
>         if (phone) {
>           // Prevent scrolling body when swiping the backdrop
>           this.backdropElement.addEventListener('touchmove', function(e) {
> ```

Instead of preventing the move, what should actually happen is that the overlay is closed:

```js
if (phone) {
  this.listen(this.backdropElement, 'touchstart', 'close');
} else {
  this.unlisten(this.backdropElement, 'touchstart', 'close');
}
```

---

*[vaadin-context-menu-overlay.html, line 87 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KXuUEdk4h8MrAq4-VC4:-KXuUEdlpoIMq2VsQEXs:b9xv23c) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b94ae5f72b56cc3e2b964f59cec8ee01ef621bc/vaadin-context-menu-overlay.html#L87)):*
> ```HTML
>           // Prevent scrolling body when swiping the overlay, but
>           // only in the case of scroll position is at the edges.
>           this.addEventListener('touchstart', function(e) {
> ```

I don't think this works if the overlay isn't high enough to be scrollable. `scrollTop` will remain `0` all the time?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[vaadin-context-menu-overlay.html, line 29 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KXuV7cMLWFsQf2hw-F1:-KXucIxxD-JwW6R_qYX7:b-99juw7) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/dcf0f6dd502aec0912610b113f22e6d996f2fac7/vaadin-context-menu-overlay.html#L29)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Please don't remove this comment
</blockquote></details>

Wa not intentional

---

*[vaadin-context-menu-overlay.html, line 30 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KXu_Br_RtkwiNJNyRBP:-KXucMpbNbvJyjupUn9R:b-riolb7) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b94ae5f72b56cc3e2b964f59cec8ee01ef621bc/vaadin-context-menu-overlay.html#L30)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Seems like the address bar height is different at least in different iPhones (5/6) so we can't use `100vh - 48px` – `max-height: 80vh` seems to work best for all of them.
</blockquote></details>

I don't follow, 48px is the double of the bottom value, has nothing with do with the height of the address bar.

So setting 80vh, means that when the address bar is opened the overlay looks almost centered, but when it closes there is a bigger area at the top than at the bottom.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-context-menu-overlay.html, line 29 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KXuV7cMLWFsQf2hw-F1:-KXurNRZbRQtmo2xPTAV:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/dcf0f6dd502aec0912610b113f22e6d996f2fac7/vaadin-context-menu-overlay.html#L29)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Wa not intentional
</blockquote></details>

Done.

---

*[vaadin-context-menu-overlay.html, line 30 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KXu_Br_RtkwiNJNyRBP:-KXurMvE5qEaknrFz2x4:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b94ae5f72b56cc3e2b964f59cec8ee01ef621bc/vaadin-context-menu-overlay.html#L30)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I don't follow, 48px is the double of the bottom value, has nothing with do with the height of the address bar.

So setting 80vh, means that when the address bar is opened the overlay looks almost centered, but when it closes there is a bigger area at the top than at the bottom.
</blockquote></details>

Done.

---

*[vaadin-context-menu-overlay.html, line 82 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KXuTsA9qu9v4f_waQye:-KXut7TSy7Qt-__lK9oD:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b94ae5f72b56cc3e2b964f59cec8ee01ef621bc/vaadin-context-menu-overlay.html#L82)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Instead of preventing the move, what should actually happen is that the overlay is closed:

```js
if (phone) {
  this.listen(this.backdropElement, 'touchstart', 'close');
} else {
  this.unlisten(this.backdropElement, 'touchstart', 'close');
}
```
</blockquote></details>

Done.

---

*[vaadin-context-menu-overlay.html, line 87 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KXuUEdk4h8MrAq4-VC4:-KXut91t_VknpHbV7RTr:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b94ae5f72b56cc3e2b964f59cec8ee01ef621bc/vaadin-context-menu-overlay.html#L87)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I don't think this works if the overlay isn't high enough to be scrollable. `scrollTop` will remain `0` all the time?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37)*

**Comment by tomivirkki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[vaadin-context-menu-overlay.html, line 87 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KXuUEdk4h8MrAq4-VC4:-KXuvdKoYGeXCxxWtJV4:b-fqt1k6) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b94ae5f72b56cc3e2b964f59cec8ee01ef621bc/vaadin-context-menu-overlay.html#L87)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still only works for me when the content is scrollable. Try with the advanced.html demo for example.

---

*[vaadin-context-menu-overlay.html, line 88 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KXutMbvNMSv4sd5unvt:-KXutMbvNMSv4sd5unvu:b-8c1l7q) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/9f84d0709f94605822550b7f344e95907fde48f9/vaadin-context-menu-overlay.html#L88)):*
> ```HTML
>           // Prevent scrolling body when swiping the overlay if
>           // there is no scroll.
>           this.addEventListener('touchmove', function(e) {
> ```

```
listeners: {
  'touchmove': '_onTouchMove',
  'touchstart': '_onTouchStart'
}
```
would be cleaner. There's a lot of nested blocks in `_phoneChanged` now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-context-menu-overlay.html, line 87 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KXuUEdk4h8MrAq4-VC4:-KXyGZVlTRyPg7z9ZnRP:bgz7x2x) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0b94ae5f72b56cc3e2b964f59cec8ee01ef621bc/vaadin-context-menu-overlay.html#L87)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Still only works for me when the content is scrollable. Try with the advanced.html demo for example.
</blockquote></details>

The javascript approach of adding/removing a pixel is not very reliable. Replaced the hack with a css solution that works fine in android and ios.

---

*[vaadin-context-menu-overlay.html, line 88 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KXutMbvNMSv4sd5unvt:-KXyGVwI9VKCJI9br9fW:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/9f84d0709f94605822550b7f344e95907fde48f9/vaadin-context-menu-overlay.html#L88)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

```
listeners: {
  'touchmove': '_onTouchMove',
  'touchstart': '_onTouchStart'
}
```
would be cleaner. There's a lot of nested blocks in `_phoneChanged` now
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37)*

**Comment by tomivirkki** [comment]
*[vaadin-context-menu-overlay.html, line 34 at r6](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KYOqJnI3ijw4M3wHrXN:-KYOqJnI9LQ74KOuCjjJ:b-14vrub) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/81c08f5944d8e6488703e230ab000d6a34e39ffa/vaadin-context-menu-overlay.html#L34)):*
> ```HTML
>         /* Ideally should be 100vh - 2*24px but iOS phone has issues when the addr-bar activates */
>         max-height: 80vh;
>         bottom: 24px;
> ```

Hmm....why the switch from bottom: 0 + padding: 24px => bottom: 24px + padding 0 24px; ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[vaadin-context-menu-overlay.html, line 34 at r6](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KYOqJnI3ijw4M3wHrXN:-KYTVyQPuK1QhtEGeGf-:b-bw0kzq) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/81c08f5944d8e6488703e230ab000d6a34e39ffa/vaadin-context-menu-overlay.html#L34)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Hmm....why the switch from bottom: 0 + padding: 24px => bottom: 24px + padding 0 24px; ?
</blockquote></details>

So as the bottom area (24px) is part of the backdrop instead of the context menu.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37)*

**Comment by tomivirkki** [comment]
*[test/touch.html, line 92 at r7](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KYXnSdBiJn1_Tq75nJM:-KYXnSdBiJn1_Tq75nJN:bela8z9) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/8e5b8f03ec3de415c9ef320c7dbcc9667986e0aa/test/touch.html#L92)):*
> ```HTML
>           expect(styles.transform).not.to.contain('translate');
>           done();
>         }, 1000);
> ```

No timeouts, please. Listen to 'iron-overlay-opened' event

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37)*

**Comment by tomivirkki** [comment]
Still not working as it should:

The vertical scrollbar should be inside the container, currently it's outside like:
screenshot 2016-12-09 14 36 11

The menu isn't aligned to bottom. Here's the first demo on IOS simulator:

screenshot 2016-12-09 15 37 18

**Comment by tomivirkki** [comment]
*[test/touch.html, line 92 at r7](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KYXnSdBiJn1_Tq75nJM:-KYrRB8R_8aVnWo9Kd-_:bb6thi3) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/8e5b8f03ec3de415c9ef320c7dbcc9667986e0aa/test/touch.html#L92)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

No timeouts, please. Listen to 'iron-overlay-opened' event
</blockquote></details>

Bump

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/touch.html, line 92 at r7](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-KYXnSdBiJn1_Tq75nJM:-KYw6-kuzbCLvFmgTdPu:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/8e5b8f03ec3de415c9ef320c7dbcc9667986e0aa/test/touch.html#L92)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Bump
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37)*

**Comment by tomivirkki** [comment]
Reviewed 5 of 5 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r9.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-:-KYwG_YBkGRqj1sBTGcn:bnfp4nl)*

**Comment by Saulis** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/37#-:-KYw_XgEYJLu-VKyzoR8:bnfp4nl)*

**Pull request merged**
