### PR TITLE
Fix overlay position

### LINKED ISSUE #115: It should be possible to define a min-width for the context menu overlay
Currently, if you open the context menu close to the right edge of the viewport, the overlay width will be really narrow.

### PR DESCRIPTION
**Pull request by manolo**
Fixes #115

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[src/vaadin-context-menu.html, line 22 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCbg0gN4C5BAqSF97mb:-LCbg0gN4C5BAqSF97mc:bo92hig) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0bcb9dd5959554f261b1c3d4c01e19796d0ce607/src/vaadin-context-menu.html#L22)):*
> ```HTML
>       }
> 
>       :host([right-aligned]) {
> ```

Should use "end-eligned" to prepare for rtl

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158)*

**Comment by tomivirkki** [comment]
*[src/vaadin-context-menu.html, line 325 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCbgl1l2g9D4amzuJu1:-LCbgl1l2g9D4amzuJu2:b-247oro) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0bcb9dd5959554f261b1c3d4c01e19796d0ce607/src/vaadin-context-menu.html#L325)):*
> ```HTML
>             // This timeout should not be necessary, because we call focus once
>             // the component has been rendered and positioned, but otherwise
>             // tests fail.
> ```

Which browsers do they fail on? Tried several and they passed on all of them.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158)*

**Comment by tomivirkki** [comment]
*[src/vaadin-context-menu.html, line 456 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCbj5NSDO_qxzJygKbj:-LCbj5NSDO_qxzJygKbk:b-j5ur2p) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0bcb9dd5959554f261b1c3d4c01e19796d0ce607/src/vaadin-context-menu.html#L456)):*
> ```HTML
> 
>           // Measure actual overlay and content sizes
>           const overlayRect = overlay.getClientRects()[0];
> ```

Isn't this the same as `

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158)*

**Comment by tomivirkki** [comment]
*[src/vaadin-context-menu.html, line 456 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCbj5NSDO_qxzJygKbj:-LCbjAqE2cNZUsMe018m:bwjmmed) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0bcb9dd5959554f261b1c3d4c01e19796d0ce607/src/vaadin-context-menu.html#L456)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Isn't this the same as `
</blockquote></details>

...as getBoundingClientRect()

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158)*

**Comment by tomivirkki** [comment]
*[src/vaadin-context-menu.html, line 485 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCbjVZN2xtXE4jLXe-y:-LCbjVZN2xtXE4jLXe-z:bu8zr3t) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0bcb9dd5959554f261b1c3d4c01e19796d0ce607/src/vaadin-context-menu.html#L485)):*
> ```HTML
>         }
> 
>         __getEventCoordinate(event, coord) {
> ```

Turning protected members into private ones is a breaking change and would require a major release

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/vaadin-context-menu.html, line 22 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCbg0gN4C5BAqSF97mb:-LCbwM9R839mVwg2dwQD:bmqhf9q) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0bcb9dd5959554f261b1c3d4c01e19796d0ce607/src/vaadin-context-menu.html#L22)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should use "end-eligned" to prepare for rtl
</blockquote></details>

I took this from `date-picker` 

---

*[src/vaadin-context-menu.html, line 325 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCbgl1l2g9D4amzuJu1:-LCbwZK32FynA7Ljoq96:b-2a1gbb) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0bcb9dd5959554f261b1c3d4c01e19796d0ce607/src/vaadin-context-menu.html#L325)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Which browsers do they fail on? Tried several and they passed on all of them.
</blockquote></details>

It failed in travis local chrome, will double check

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158)*

**Comment by tomivirkki** [comment]
*[src/vaadin-context-menu.html, line 22 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCbg0gN4C5BAqSF97mb:-LCc4mfUC1KPYqmhqujW:b7gc69i) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0bcb9dd5959554f261b1c3d4c01e19796d0ce607/src/vaadin-context-menu.html#L22)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I took this from `date-picker` 
</blockquote></details>

Ok, let's fix this for both components at the same time then (separate task)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/vaadin-context-menu.html, line 325 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCbgl1l2g9D4amzuJu1:-LCcMKw25nzrVBIk5A9S:b-mhkh9t) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0bcb9dd5959554f261b1c3d4c01e19796d0ce607/src/vaadin-context-menu.html#L325)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

It failed in travis local chrome, will double check
</blockquote></details>

Seems working now. Done

---

*[src/vaadin-context-menu.html, line 456 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCbj5NSDO_qxzJygKbj:-LCcMGtl6Vxg-N9gOUjq:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0bcb9dd5959554f261b1c3d4c01e19796d0ce607/src/vaadin-context-menu.html#L456)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

...as getBoundingClientRect()
</blockquote></details>

Done.

---

*[src/vaadin-context-menu.html, line 485 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCbjVZN2xtXE4jLXe-y:-LCcMEvm7MSBs__u0t74:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0bcb9dd5959554f261b1c3d4c01e19796d0ce607/src/vaadin-context-menu.html#L485)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Turning protected members into private ones is a breaking change and would require a major release
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158)*

**Comment by tomivirkki** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[src/vaadin-context-menu.html, line 447 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCiLJ3V2vu0Aa_UBCKk:-LCiLJ3V2vu0Aa_UBCKl:bc2kmv2) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/06dffbf4205985edb9eb269c32cdcf7b35bae34d/src/vaadin-context-menu.html#L447)):*
> ```HTML
> 
>           // Reset all properties before measuring
>           ['top', 'right', 'bottom', 'left'].forEach(prop => style.removeProperty(prop));
> ```

Untested code

---

*[src/vaadin-context-menu.html, line 448 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCiLL4t-HmghvSglLjk:-LCiLL4t-HmghvSglLjl:bc2kmv2) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/06dffbf4205985edb9eb269c32cdcf7b35bae34d/src/vaadin-context-menu.html#L448)):*
> ```HTML
>           // Reset all properties before measuring
>           ['top', 'right', 'bottom', 'left'].forEach(prop => style.removeProperty(prop));
>           ['right-aligned', 'bottom-aligned'].forEach(attr => overlay.removeAttribute(attr));
> ```

Untested code

---

*[src/vaadin-context-menu.html, line 475 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCiIxel1W3zkDYskNFx:-LCiIxel1W3zkDYskNFy:bc2kmv2) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/06dffbf4205985edb9eb269c32cdcf7b35bae34d/src/vaadin-context-menu.html#L475)):*
> ```HTML
>             style.top = y + 'px';
>           } else {
>             style.bottom = (hghtVport - y) + 'px';
> ```

Untested code

---

*[test/overlay.html, line 101 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCiJ-hB5RJXZuDoVbFa:-LCiJ-hB5RJXZuDoVbFb:b-bsh23l) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/06dffbf4205985edb9eb269c32cdcf7b35bae34d/test/overlay.html#L101)):*
> ```HTML
>           it('should be aligned relative to top-left corner', done => {
>             listenOnce(menu.$.overlay, 'vaadin-overlay-open', () => {
>               expect(menu.$.overlay.hasAttribute('right-aligned')).to.be.false;
> ```

These test are testing the implementation (presence of some internal attribute) rather that the expected behaviour. If someone would accidentally remove the new styles added for "right-aligned" and "bottom-aligned", all the tests would still pass but the element would be broken. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[src/vaadin-context-menu.html, line 447 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCiLJ3V2vu0Aa_UBCKk:-LCopZyO0lkFb5OQayfj:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/06dffbf4205985edb9eb269c32cdcf7b35bae34d/src/vaadin-context-menu.html#L447)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Untested code
</blockquote></details>

Done.

---

*[src/vaadin-context-menu.html, line 448 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCiLL4t-HmghvSglLjk:-LCop__L4aE43GexQOOf:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/06dffbf4205985edb9eb269c32cdcf7b35bae34d/src/vaadin-context-menu.html#L448)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Untested code
</blockquote></details>

Done.

---

*[src/vaadin-context-menu.html, line 475 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCiIxel1W3zkDYskNFx:-LCosVVJ1P0_LFT7OwnD:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/06dffbf4205985edb9eb269c32cdcf7b35bae34d/src/vaadin-context-menu.html#L475)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Untested code
</blockquote></details>

Done.

---

*[test/overlay.html, line 101 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LCiJ-hB5RJXZuDoVbFa:-LCosb7D45hv7X7Krbna:bdz0kud) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/06dffbf4205985edb9eb269c32cdcf7b35bae34d/test/overlay.html#L101)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

These test are testing the implementation (presence of some internal attribute) rather that the expected behaviour. If someone would accidentally remove the new styles added for "right-aligned" and "bottom-aligned", all the tests would still pass but the element would be broken. 
</blockquote></details>

added assertions in tests  to actually measure overlay position.  Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158)*

**Comment by YuriyVaadin** [comment]
Other than small nit, :lgtm: 

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/vaadin-context-menu.html, line 317 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-LD0eyLKC4ugWVI3wcw6:-LD0eyLKC4ugWVI3wcw7:b-7s8g5q) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/869e09f03faa8e958c51fd7489940865c4e870b6/src/vaadin-context-menu.html#L317)):*
> ```HTML
>         // Runs after overlay is fully rendered
>         _onVaadinOverlayOpen(e) {
>           if (this.opened) {
> ```

Nit: Why this check is required?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-:-LD0fc3f4-_vS9yC5qB2:b6yo5t6)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158#-:-LD10nzuCk1y2Zy-Wm8F:bnfp4nl)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 3 files at r1, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/158)*

**Pull request merged**
