### PR TITLE
Fix iOS closing the overlay in first touch.

### PR DESCRIPTION
**Pull request by manolo**
Regression after iron-overlay-behavior version 1.10.2

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/75)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/75#-:-Kjqdbif_ootiHzGjMrS:bnfp4nl)*

**Comment by Saulis** [comment]
I think we should also update `bower.json` to have `iron-overlay-behavior` `^1.10.3`

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[test/touch.html, line 158 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/75#-Kjr8Gc1aC73n90dTrZ_:-Kjr8Gc1aC73n90dTrZa:biqlibo) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/9003102d39141aa6c8011072eecf4330280fdda4/test/touch.html#L158)):*
> ```HTML
>           makeSoloTouchEvent('touchstart', xy, target);
> 
>           menu.async(function() {
> ```

We should listen to `iron-overlay-opened` instead of using `async` and 600ms delay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/75#-:-Kjr8M1tJNNxRdREphbp:b-3vdqw2)*

**Comment by manolo** [comment]
Since the Hybrid PR is coming and reviewed, it's already based on this, and it updates the bower.json  appropriately I would leave this PR as it is.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/touch.html, line 158 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/75#-Kjr8Gc1aC73n90dTrZ_:-Kk0Q5PuFvaHpR4agZDJ:b-58q8n3) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/9003102d39141aa6c8011072eecf4330280fdda4/test/touch.html#L158)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

We should listen to `iron-overlay-opened` instead of using `async` and 600ms delay.
</blockquote></details>

This is already changed in the Hybrid PR, so it's not important to change in this PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/75#-:-Kk0Pb6cBvQ92gx9QFYT:baq94ci)*

**Comment by Saulis** [comment]
Fixed by #76

**Pull request merged**
