### PR TITLE
Update usage example and screenshot in README.md

### PR DESCRIPTION
**Pull request by platosha**
The code example in the README is changed to use less features and code,
while still demonstrating a practical use case. The screenshot now
matches the code example.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/59)

### CODE REVIEW

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 39 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/59#-KZ_ndM78dWrh1jxwN3b:-KZ_ndM78dWrh1jxwN3c:b-9qla1h) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b82cb551408c6f310dc80f750e9a4240585e308e/README.md#L39)):*
> ```Markdown
>   </template>
> 
>   <p>This paragraph has the context menu provided in the above template.</p>
> ```

I would add some wording to invite the user to right-click or long-tap, like : 

"This paragraph has the context menu provided in the above template, right-click or long-tap on this to show it"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/59)*

**Comment by platosha** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 39 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/59#-KZ_ndM78dWrh1jxwN3b:-KZak4fdquew-TuhUPHJ:bybbzkk) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b82cb551408c6f310dc80f750e9a4240585e308e/README.md#L39)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I would add some wording to invite the user to right-click or long-tap, like : 

"This paragraph has the context menu provided in the above template, right-click or long-tap on this to show it"
</blockquote></details>

It is too late. The screenshot is matching this text, and is also used for the same example code in the docs.

Also, the screenshot can not actually respond on right-click, it’s a static image. Inviting users could confuse them there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/59)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/59#-:-KZalbZsU-Bz7ngl63M1:bnfp4nl)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 39 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/59#-KZ_ndM78dWrh1jxwN3b:-KZasKM2ETaWjk4geIL0:b-1hf8bi) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b82cb551408c6f310dc80f750e9a4240585e308e/README.md#L39)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

It is too late. The screenshot is matching this text, and is also used for the same example code in the docs.

Also, the screenshot can not actually respond on right-click, it’s a static image. Inviting users could confuse them there.
</blockquote></details>

Could then we make the screenshot a .gif animation, so as the user can figure out how the demo works ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/59)*

**Comment by platosha** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 39 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/59#-KZ_ndM78dWrh1jxwN3b:-KZg0kLEaJiCdEfy408f:b9oh3br) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b82cb551408c6f310dc80f750e9a4240585e308e/README.md#L39)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Could then we make the screenshot a .gif animation, so as the user can figure out how the demo works ? 
</blockquote></details>

Maybe, but IMO it is not a necessary requirement here to have animation. In general, it should be understandable what does this example code do, even from a static image. This was in my goals when making the screenshots.

Since we have “context menu” in the element and repo names, the names themselves already tell enough about how to open it.

I don’t feel like we should explain how to open context menus in here. Unless the context menu does not open by right click, which is, fortunately, not the case.

Please look at the code example and the screenshot combined together: https://github.com/vaadin/vaadin-context-menu/blob/080a3e4458a99ba0ac7d94b76fe3c3155957b611/README.md

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/59)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/59#-:-K_9J8okNnhbi4O0RAIV:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/59)*

**Pull request merged**
