### PR TITLE
Upgrade to vaadin-overlay ^3.0.0

### LINKED ISSUE #149: Use overlay 3.0
- Start from proto/style-gather
- Update the demo

### PR DESCRIPTION
**Pull request by limonte**
Fixes #149 

Connected to https://github.com/vaadin/vaadin-overlay/pull/76

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/150)

### CODE REVIEW

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150#-:-LAN7mGv2lgWijRQgXzQ:bnfp4nl)*

**Comment by platosha** [comment]
Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150#-LAN78MF1-QUeXd1JVf2:-LAN78MF1-QUeXd1JVf3:b-ymwws) (no related file):*
The ticket says “Update the demo”. Despite it is not explanatory enough, the background behind is:

- Now that a new way for overlay content styling is available, we should document it.
- Documentation only in the overlay component is not sufficient, as it the overlay is not intended for public use.

In this component, in the “Advanced Usage” page, there is a “Basic HTML Menu” demo that suggests how to build a styled menu. Currently, this uses styles inside template, which are not adequately scoped when using with ShadyDOM, and leak to global scope. We should update that demo to demonstrate styling the overlay content from the parent scope instead.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150)*

**Comment by tomivirkki** [comment]
Same as https://github.com/vaadin/vaadin-notification/pull/64#issuecomment-382332518. Prefixing a branch that's supposed to contain stable code to be merged to master as "proto" doesn't sound quite right. As there's alsready a LGTM and more comments, let's not close this.

**Comment by tomivirkki** [comment]
*[src/vaadin-context-menu.html, line 383 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150#-LANN_2864WJQVxWaWN8:-LANNTqG4xTvjscI8vwQ:b-mnaxlf) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/e649f22ed8cf81aeb8b02da61a5d67f30c7697ba/src/vaadin-context-menu.html#L383)):*
> ```HTML
>             return;
>           }
>           this._instance.detail = context.detail;
> ```

Why this change? "instance" is a dependency of this observer function so the previous version was cleaner. See https://www.polymer-project.org/2.0/docs/devguide/observers#dependencies

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150)*

**Comment by limonte** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150#-LAN78MF1-QUeXd1JVf2:-LANOTWW8VVk-MeY5fN5:b-inme35) (no related file):*
> In this component, in the “Advanced Usage” page, there is a “Basic HTML Menu” demo that suggests how to build a styled menu. Currently, this uses styles inside template, which are not adequately scoped when using with ShadyDOM, and leak to global scope. We should update that demo to demonstrate styling the overlay content from the parent scope instead.

Done.

---

*[src/vaadin-context-menu.html, line 383 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150#-LANN_2864WJQVxWaWN8:-LANOYlA2MQwG9Lv5rUI:byuf4vw) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/e649f22ed8cf81aeb8b02da61a5d67f30c7697ba/src/vaadin-context-menu.html#L383)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why this change? "instance" is a dependency of this observer function so the previous version was cleaner. See https://www.polymer-project.org/2.0/docs/devguide/observers#dependencies
</blockquote></details>

Roger.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150)*

**Comment by limonte** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-context-menu.html, line 383 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150#-LANN_2864WJQVxWaWN8:-LANQlkMAjj6ObLy3FmV:b-c48hb6) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/e649f22ed8cf81aeb8b02da61a5d67f30c7697ba/src/vaadin-context-menu.html#L383)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Roger.
</blockquote></details>

Done. The previous comment was to the "Prefixing a branch that's supposed to contain stable code to be merged to master as "proto" doesn't sound quite right." comment.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[demo/context-menu-advanced-demos.html, line 118 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150#-LANRPsFE4AvPeH_KkYL:-LANRPsFE4AvPeH_KkYM:b-4stkyb) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/3d62cef2fb5c484b0d68659b292fd88f857871b8/demo/context-menu-advanced-demos.html#L118)):*
> ```HTML
>               text-decoration: none;
>               color: var(--lumo-success-text-color);
>             }
> ```

please add an empty line here to make stylelint happy

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150)*

**Comment by tomivirkki** [comment]
*[demo/context-menu-advanced-demos.html, line 112 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150#-LANRsNR3U5X6MMy_ERG:-LANRsNR3U5X6MMy_ERH:bvguifl) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/3d62cef2fb5c484b0d68659b292fd88f857871b8/demo/context-menu-advanced-demos.html#L112)):*
> ```HTML
>       <template preserve-content>
>         <vaadin-context-menu>
>           <style>
> ```

The style tag should not be inside "vaadin-context-menu" element

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150)*

**Comment by limonte** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/context-menu-advanced-demos.html, line 118 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150#-LANRPsFE4AvPeH_KkYL:-LANRs084jgOMXs0s-p_:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/3d62cef2fb5c484b0d68659b292fd88f857871b8/demo/context-menu-advanced-demos.html#L118)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

please add an empty line here to make stylelint happy
</blockquote></details>

done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150)*

**Comment by limonte** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/context-menu-advanced-demos.html, line 112 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150#-LANRsNR3U5X6MMy_ERG:-LANSIQn4mlHuk4t_Tbi:b-8c7yla) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/3d62cef2fb5c484b0d68659b292fd88f857871b8/demo/context-menu-advanced-demos.html#L112)):*
> The style tag should not be inside "vaadin-context-menu" element

oops, done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 2 files at r3, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/150#-:-LANUy6mBlOwM8JJ_i4T:bnfp4nl)*

**Pull request merged**
