### PR TITLE
Convert to pure Polymer2 ES6

### PR DESCRIPTION
**Pull request by tomivirkki**
Connects to #77

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/82)

### CODE REVIEW

**Comment by platosha** [comment]
:thumbsup: Very good job!

---

Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-context-menu-overlay.html, line 49 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-KmWZiXFsqK9lINzxGg6:-KmWZiXFsqK9lINzxGg7:bo7ppc6) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b63d33b51be1cc6e23008c5d9d2ff745e8b3c642/vaadin-context-menu-overlay.html#L49)):*
> ```HTML
>   </template>
>   <script>
>     (function() {
> ```

We should probably throw an error here if Polymer 1 is used. See the skeleton for an example.

---

*[vaadin-context-menu.html, line 32 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-KmW_6uhFpuZ_Tp8jZmx:-KmW_6uhFpuZ_Tp8jZmy:b-omyq3m) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b63d33b51be1cc6e23008c5d9d2ff745e8b3c642/vaadin-context-menu.html#L32)):*
> ```HTML
>   </template>
>   <script>
>     (function() {
> ```

Maybe throw an error for Polymer 1 here too.

---

*[vaadin-contextmenu-event.html, line 52 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-KmWajHAUWhr_qXVZTlT:-KmWajHAUWhr_qXVZTlU:bvmeu69) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b63d33b51be1cc6e23008c5d9d2ff745e8b3c642/vaadin-contextmenu-event.html#L52)):*
> ```HTML
>           // For code readability, findOriginalTarget() should be
>           // changed to use composedPath() directly after native Shadow becomes the norm.
>           const t = Polymer.Gestures.findOriginalTarget(e) || e.target;
> ```

`findOriginalTarget` is deprecated. Note the comment above that suggests removing this.

We can probably do the same right here: https://github.com/Polymer/polymer/blob/2ed0a07e00a1102e248576ca5390f2b6257a3ee5/lib/utils/gestures.html#L268 

---

*[vaadin-contextmenu-event.html, line 87 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-KmWaG3skx7e1ZcMI6ZB:-KmWaG3tSCWDEpIyutos:bd2j5ce) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b63d33b51be1cc6e23008c5d9d2ff745e8b3c642/vaadin-contextmenu-event.html#L87)):*
> ```HTML
> 
>       fire: function(target, x, y) {
>         // 2.0 has moved _fire method to private API
> ```

Perhaps we don’t need this comment anymore.

---

*[demo/index.html, line 116 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-KmWbmX50LCnfjHgzNg1:-KmWbmX50LCnfjHgzNg2:bniwtdc) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b63d33b51be1cc6e23008c5d9d2ff745e8b3c642/demo/index.html#L116)):*
> ```HTML
>           </template>
> 
>           <script>
> ```

BTW not a blocker, but some of the demos are wrapped in `WebComponentsReady` event, and the others not. Maybe wrap all the demos defining elements?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-:-KmWgxBblAkJJ6X_1E8F:b9s16y8)*

**Comment by platosha** [comment]
Just noticed: this does not seem to add theming.

We have a CSS mixin for the overlay, should we replace it in this PR?

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-:-Km_iY5va4wHvuDgAk5a:b-urebw)*

**Comment by tomivirkki** [comment]
Was planning on doing that in a separate PR. There's a branch for it already.

---

Review status: 23 of 27 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-context-menu-overlay.html, line 49 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-KmWZiXFsqK9lINzxGg6:-KmWmX7qiOsSdPgYBc6z:b-33y6k5) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b63d33b51be1cc6e23008c5d9d2ff745e8b3c642/vaadin-context-menu-overlay.html#L49)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

We should probably throw an error here if Polymer 1 is used. See the skeleton for an example.
</blockquote></details>

Maybe just 1 error is enough (by vaadin-context-menu)

---

*[vaadin-context-menu.html, line 32 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-KmW_6uhFpuZ_Tp8jZmx:-KmWmf6RP9wGfNFL_ltn:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b63d33b51be1cc6e23008c5d9d2ff745e8b3c642/vaadin-context-menu.html#L32)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Maybe throw an error for Polymer 1 here too.
</blockquote></details>

Done.

---

*[vaadin-contextmenu-event.html, line 52 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-KmWajHAUWhr_qXVZTlT:-Kma8HaJ8wnGiAGR4rdE:bo44jhh) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b63d33b51be1cc6e23008c5d9d2ff745e8b3c642/vaadin-contextmenu-event.html#L52)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

`findOriginalTarget` is deprecated. Note the comment above that suggests removing this.

We can probably do the same right here: https://github.com/Polymer/polymer/blob/2ed0a07e00a1102e248576ca5390f2b6257a3ee5/lib/utils/gestures.html#L268 
</blockquote></details>

Hmm...that's exactly what `Polymer.Gestures.findOriginalTarget(e)` does under the hood. Why would we want to extract the code from the function?

The API is also public so I guess it can't really disappear before Polymer 3 even if it was deprecated.

---

*[vaadin-contextmenu-event.html, line 87 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-KmWaG3skx7e1ZcMI6ZB:-Kma7KGoJLgNSn9Zn0_G:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b63d33b51be1cc6e23008c5d9d2ff745e8b3c642/vaadin-contextmenu-event.html#L87)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Perhaps we don’t need this comment anymore.
</blockquote></details>

Done.

---

*[demo/index.html, line 116 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-KmWbmX50LCnfjHgzNg1:-KmaADmGjmNRPtpq0CSK:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b63d33b51be1cc6e23008c5d9d2ff745e8b3c642/demo/index.html#L116)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW not a blocker, but some of the demos are wrapped in `WebComponentsReady` event, and the others not. Maybe wrap all the demos defining elements?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-:-Km_lFTNGkTOfVsV_wgA:bo313f6)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-context-menu-overlay.html, line 49 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-KmWZiXFsqK9lINzxGg6:-KmaAcuSu7M4u1heenpS:b32w0x) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b63d33b51be1cc6e23008c5d9d2ff745e8b3c642/vaadin-context-menu-overlay.html#L49)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Maybe just 1 error is enough (by vaadin-context-menu)
</blockquote></details>

OK

---

*[vaadin-contextmenu-event.html, line 52 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-KmWajHAUWhr_qXVZTlT:-KmaAqM6Xhkx0xRqzJym:b-oa9040) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b63d33b51be1cc6e23008c5d9d2ff745e8b3c642/vaadin-contextmenu-event.html#L52)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Hmm...that's exactly what `Polymer.Gestures.findOriginalTarget(e)` does under the hood. Why would we want to extract the code from the function?

The API is also public so I guess it can't really disappear before Polymer 3 even if it was deprecated.
</blockquote></details>

OK. As the comment says, for code readability. Not a blocker though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-:-KmaBNQWeXn9N1zzk2wX:bnfp4nl)*

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82)*

**Comment by limonte** [comment]
nicely done endeed! :+1:

---

Reviewed 22 of 27 files at r1, 3 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[bower.json, line 22 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-KmaqgIHnRryEr_eB3BR:-KmaqgIINW6gklOp5Tys:b-ifhm4p) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/8e8dccd97e2e1a6a940db6d60ad1c22431456abe/bower.json#L22)):*
> ```JSON
>     "test",
>     "gulpfile.js",
>     "package.json",
> ```

I would like not to have the `package.json` ignored for the purpose of being able to check the installed version.

---

*[index.html, line 12 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-Kmaqual6nxlXp7Na4Zb:-Kmaqual6nxlXp7Na4Zc:b-nmy8em) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/8e8dccd97e2e1a6a940db6d60ad1c22431456abe/index.html#L12)):*
> ```HTML
>   </head>
>   <body>
>     <api-doc-viewer url="documentation.json" element-class-name="Vaadin.ContextMenuElement"></api-doc-viewer>
> ```

As Sauli mentioned [here](https://www.flowdock.com/app/vaadin/elements-team/threads/H0DHYCXx0MVkS69uBpPI3bPo1Zz), `iron-component-page` should now work. Could you please try it?

---

*[package.json, line 3 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-KmarMBLh2IzshLoaIiI:-KmarMBLh2IzshLoaIiJ:b-93b8lm) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/8e8dccd97e2e1a6a940db6d60ad1c22431456abe/package.json#L3)):*
> ```JSON
> {
>   "name": "vaadin-context-menu",
>   "version": "3.0.0-alpha1",
> ```

hopefully, some nice sunny day we will be able to get out of the permanent alpha state of our elements :D

---

*[test/common.js, line 11 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-Kmarx9eIVfmvQGRvi0s:-Kmarx9eIVfmvQGRvi0t:b-tbp2ny) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/8e8dccd97e2e1a6a940db6d60ad1c22431456abe/test/common.js#L11)):*
> ```JavaScript
> 
> window.fire = (node, evType, detail) => {
>   const evt = new CustomEvent(evType, {bubbles: true, composed: true, cancelable: true, detail: detail});
> ```

it's traditionally `e` or `event`. In this case `event` and `eventType` will be much readable names.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-:-KmasTW1MlbeiA-Q_sjw:bt65sdr)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[bower.json, line 22 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-KmaqgIHnRryEr_eB3BR:-KmeOcTBmCmGxxrKa4wy:bcfowcy) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/8e8dccd97e2e1a6a940db6d60ad1c22431456abe/bower.json#L22)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I would like not to have the `package.json` ignored for the purpose of being able to check the installed version.
</blockquote></details>

It's aligned with the skeleton. All this kind of stuff should initiate from there and then be cloned to each component so that we don't end up with components that all look a bit different.

---

*[index.html, line 12 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-Kmaqual6nxlXp7Na4Zb:-KmeP3yoNIS13_k3a6Lx:b-v0tnx3) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/8e8dccd97e2e1a6a940db6d60ad1c22431456abe/index.html#L12)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

As Sauli mentioned [here](https://www.flowdock.com/app/vaadin/elements-team/threads/H0DHYCXx0MVkS69uBpPI3bPo1Zz), `iron-component-page` should now work. Could you please try it?
</blockquote></details>

Let's not experiment in this PR but try for Skeleton instead

---

*[package.json, line 3 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-KmarMBLh2IzshLoaIiI:-KmePonrPYrKJO5iJkMl:b2nhtan) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/8e8dccd97e2e1a6a940db6d60ad1c22431456abe/package.json#L3)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

hopefully, some nice sunny day we will be able to get out of the permanent alpha state of our elements :D
</blockquote></details>

Yup

---

*[test/common.js, line 11 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-Kmarx9eIVfmvQGRvi0s:-KmePepsEZDOS6eK6HfW:b-qkwz4v) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/8e8dccd97e2e1a6a940db6d60ad1c22431456abe/test/common.js#L11)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

it's traditionally `e` or `event`. In this case `event` and `eventType` will be much readable names.
</blockquote></details>

I think I derived the name from here: https://github.com/Polymer/polymer/blob/master/lib/utils/gestures.html#L384

Anyway, changed to more readable `eventType`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/82#-:-KmeU9V3l5PKO8jxWD9T:bnfp4nl)*

**Pull request merged**
