### PR TITLE
Enable visual tests with Lumo

### PR DESCRIPTION
**Pull request by samiheikki**
Connects to https://github.com/vaadin/components-team-tasks/issues/314

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/156)

### CODE REVIEW

**Comment by manolo** [comment]
Rebased with master and there are screenshots changes,  @samiheikki  can you update?

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/156#-:-LD2TmSMBuwscoV9N8bc:b-w5yglo)*

**Comment by samiheikki** [comment]
@manolo done

**Comment by manolo** [comment]
long-menu tests cut the menu at the bottom because the capture area do not cover all the viewport.
I don't know if we can capture somehow  a taller image so as we can  see that the overlay adapts to the viewport.
Note that the overlay is teleported to the body, so capturing default `<div id="default-tests"` might not be enough

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/156#-:-LD6Xahs3a_GLY76oJ68:b-z63au6)*

**Comment by manolo** [comment]
@samiheikki  I configured the test so as all the viewport is captured. Also added tests for last feature for overlay position.

---

Reviewed 17 of 17 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/156#-:-LDHgsNa-1_KC4XvjdIB:bdhaekf)*

**Comment by manolo** [comment]
:lgtm:  

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/156#-:-LDHhG4K6N4S9uLmfHsB:b593w5t)*

**Pull request merged**
