### PR TITLE
Add constrained overlay alignment / sizing support

### LINKED ISSUE #97: Can not scroll the Long Menu demo
Can not scroll the Long Menu demo on desktop nor touch (iOS 10)

### PR DESCRIPTION
**Pull request by platosha**
Fixes #97
Depends on vaadin/vaadin-overlay#25

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/99)

### CODE REVIEW

**Comment by limonte** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-context-menu.html, line 68 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/99#-Ku3DE9QgykO6TqhJlPF:-Ku3DE9QgykO6TqhJlPG:b-bz2wnl) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/c03b886051f73f770809ae92fe79956855656315/vaadin-context-menu.html#L68)):*
> ```HTML
>         with-backdrop="[[_phone]]"
>         phone$="[[_phone]]">
>     </vaadin-overla-context-menuy>
> ```

you're trying to exit Vim? :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/99)*

**Comment by YuriyVaadin** [comment]
There are some test failing on IE11 in CI and mobile (tested on iPhone 6).

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/99#-:-Ku3TG9BbkREABTGmlqU:btrkx76)*

**Comment by platosha** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-context-menu.html, line 68 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/99#-Ku3DE9QgykO6TqhJlPF:-Ku4ekoTtpEFc2Iki49U:b-urog43) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/c03b886051f73f770809ae92fe79956855656315/vaadin-context-menu.html#L68)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

you're trying to exit Vim? :D
</blockquote></details>

Done :man_facepalming:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/99)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/99#-:-KuJ2MNJON3UsTQczokS:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/99#-:-KuJ9S2rBFeLZjAk-6k3:bnfp4nl)*

**Pull request merged**
