### PR TITLE
Intuitive demo text

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Changing first basic demo text, removing comment for property-effect.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/93)

### CODE REVIEW

**Comment by samiheikki** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/index.html, line 33 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/93#-Kqg_VdfXPnRYmw_9HOt:-Kqg_Vdgaq_BJqKn6VNl:b-9n0fgg) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/3899cdb3991326402b36bc79932c51353e5040c2/demo/index.html#L33)):*
> ```HTML
> 
>           <p>This paragraph has the context menu provided in the above template.</p>
>           <p>Another paragraph with the context menu that can be opened with <b>right click.</b></p>
> ```

Can you add `or with <b>long touch</b>` as it works like that in mobile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/93)*

**Comment by YuriyVaadin** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/index.html, line 33 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/93#-Kqg_VdfXPnRYmw_9HOt:-KqgbNf7RItcczMTOwil:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/3899cdb3991326402b36bc79932c51353e5040c2/demo/index.html#L33)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Can you add `or with <b>long touch</b>` as it works like that in mobile.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/93)*

**Comment by samiheikki** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/index.html, line 33 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/93#-Kqg_VdfXPnRYmw_9HOt:-KqgdImWFxpgd9YZYQNT:b-36v0pf) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/3899cdb3991326402b36bc79932c51353e5040c2/demo/index.html#L33)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is there a space between `click.</b>` and `or with`? :)

---

*[demo/index.html, line 24 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/93#-KqgdWK-C3BGfMZODuRi:-KqgdWK-C3BGfMZODuRj:budhtge) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/18e2f0106e78b5feb47412c5f94bed0aecbdf7e2/demo/index.html#L24)):*
> ```HTML
>     <demo-snippet>
>       <template>
>         <vaadin-context-menu close-on=''>
> ```

Was this added by design?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/93)*

**Comment by YuriyVaadin** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/index.html, line 33 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/93#-Kqg_VdfXPnRYmw_9HOt:-Kqgf6esIQHaKX1AArqW:beo29m5) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/3899cdb3991326402b36bc79932c51353e5040c2/demo/index.html#L33)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Is there a space between `click.</b>` and `or with`? :)
</blockquote></details>

Space added.

---

*[demo/index.html, line 24 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/93#-KqgdWK-C3BGfMZODuRi:-Kqgf0_KFB4SPCKfjCLR:b71pou3) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/18e2f0106e78b5feb47412c5f94bed0aecbdf7e2/demo/index.html#L24)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Was this added by design?
</blockquote></details>

Was added for testing purpose. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/93)*

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/93#-:-Kqijygss0GcNjdqw0Wo:bnfp4nl)*

**Pull request merged**
