### PR TITLE
Add touch support

### PR DESCRIPTION
**Pull request by Saulis**
Fixes vaadin/components-team-tasks#200

Depends on #11 (rebase this branch after merging)

Scrolling is still enabled also for touch for now.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/5)

### CODE REVIEW

**Comment by tehapo** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[long-touch-gesture.html, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/5#-KRSXBTsvY2Lg5nkbv4X:-KRSXBTsvY2Lg5nkbv4Y:b6m5z6e) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/5ac2c14b5715ee20d9d20f56620cf034f5d38752/long-touch-gesture.html#L35)):*
> ```HTML
>           var ct = e.changedTouches[0];
>           this.fire(t, ct);
>         }.bind(this), 650);
> ```

Would 500ms be a better timeout here? At least based on a quick googling session it seems to be the default on iOS and Android. :)

iOS
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UILongPressGestureRecognizer_Class/#//apple_ref/occ/instp/UILongPressGestureRecognizer/minimumPressDuration

Android
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/ViewConfiguration.java#64

---

*[vaadin-context-menu.html, line 14 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/5#-KRSp3VTOWJqLypNZ1yd:-KRSp3VTOWJqLypNZ1ye:b-blyb1f) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/5ac2c14b5715ee20d9d20f56620cf034f5d38752/vaadin-context-menu.html#L14)):*
> ```HTML
> 
>       #overlay {
>         @apply(--shadow-elevation-6dp);
> ```

I think this shadow should not be applied when the overlay is in narrow viewport mode. Perhaps this should be moved to the `vaadin-context-menu-overlay` anyways and in there only applied when in desktop mode.

---

*[test/touch.html, line 79 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/5#-KRSVjxbB_hNBkfacz1o:-KRSVjxcHgt1XK_yQmYL:b-f7dpxl) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/5ac2c14b5715ee20d9d20f56620cf034f5d38752/test/touch.html#L79)):*
> ```HTML
>         });
>       }
> ```

Remove extra line break here to satisfy the linter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/5)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[long-touch-gesture.html, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/5#-KRXoZR-878akoBnz7AW:-KRXoZR-878akoBnz7AX:b-5prmv6) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/5ac2c14b5715ee20d9d20f56620cf034f5d38752/long-touch-gesture.html#L1)):*
> ```HTML
> <script>
> ```

Shouldn't this file import polymer.js since it depends on it ?

---

*[vaadin-context-menu-overlay.html, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/5#-KRXp1Mwn5Cooo9uztcm:-KRXp1MxIQLshznczA61:b-qmtlo5) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/5ac2c14b5715ee20d9d20f56620cf034f5d38752/vaadin-context-menu-overlay.html#L16)):*
> ```HTML
> 
>         top: 0;
>         left: 0;
> ```

I think these should be in the not desktop block, or there are any reason I don't see ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/5)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[long-touch-gesture.html, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/5#-KRXoZR-878akoBnz7AW:-KRYTYInb5NsrXXYG4kn:bhkd0jc) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/5ac2c14b5715ee20d9d20f56620cf034f5d38752/long-touch-gesture.html#L1)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Shouldn't this file import polymer.js since it depends on it ?
</details>
I meant polymer.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/5)*

**Comment by samiheikki** [comment]
Reviewed 4 of 15 files at r2, 4 of 11 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[test/touch.html, line 88 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/5#-KS0yF7Sd6i2TmYtYSmR:-KS0yF7Sd6i2TmYtYSmS:b75923e) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/9d00d2b8dfd8f497d1a081effee144f4a3dcd821/test/touch.html#L88)):*
> ```HTML
>       it('should open on long-touch on ios', function(done) {
>         menu._ios = true;
>         makeSoloTouchEvent('touchstart', null, menu.listenOn);
> ```

Can you set some extra line breaks here as they are in other test cases also?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/5)*

**Comment by tehapo** [comment]
Reviewed 3 of 15 files at r2, 4 of 11 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/5)*

**Comment by tomivirkki** [comment]
*[long-touch-gesture.html, line 6 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/5#-KS5GnRvxzHNeCjilGEr:-KS5GnRvxzHNeCjilGEs:b-kcntba) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/9d00d2b8dfd8f497d1a081effee144f4a3dcd821/long-touch-gesture.html#L6)):*
> ```HTML
>   (function() {
>     Polymer.Gestures.register({
>       name: 'long-touch',
> ```

This registers the gesture name globally. Is it intended for general use or should we prefix it to avoid possible (very unlikely) collisions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/5)*

**Pull request closed without merging**
