### PR TITLE
Use `<vaadin-list-box>`

### LINKED ISSUE #110: Replace paper-listbox with vaadin-list-box
Depends on:
https://github.com/vaadin/vaadin-list-mixin/issues/12
https://github.com/vaadin/vaadin-list-mixin/issues/13

### PR DESCRIPTION
**Pull request by manolo**
Fixes #110

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/111)

### CODE REVIEW

**Comment by tomivirkki** [comment]
This pr is _way_ premature. There's no point in replacing the demo elements while there isn't even a first alpha release of list-box

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/111#-:-Kx6vblVU-0hkPO6CtNJ:bgn7vt8)*

**Comment by manolo** [comment]
Yes, this is to check that everything else works, and other team member can track it.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/111#-:-Kx71MfRiHUQxiK81lEY:b3eapn0)*

**Comment by tomivirkki** [comment]
It should not be a PR then! There's a risk that someone just hits the merge button without realizing that this mustn't be merged until we have stable listbox. This will happen somewhere around in two months.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/111#-:-Kx771pQq6s7k6jCnpaR:bvmbs4z)*

**Comment by manolo** [comment]
Closing this PR right now, will be reopened when we face this task again

**Pull request closed without merging**
