### PR TITLE
Sync with element-skeleton

### PR DESCRIPTION
**Pull request by limonte**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/44)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/touch.html, line 47 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44#-KYrP2OwFu3-Pxl3RFXg:-KYrP2OwFu3-Pxl3RFXh:bwav4ob) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/48f0ff944d6f7372fcbb744577f235082f8e7f5c/test/touch.html#L47)):*
> ```HTML
> 
>         for (var property in touchEventInit) {
>           if ({}.hasOwnProperty.call(touchEventInit, property)) {
> ```

The same observation here about the `{} call` usage that I did in uploader

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44)*

**Comment by limonte** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/touch.html, line 47 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44#-KYrP2OwFu3-Pxl3RFXg:-KYrVXeI-WJXIMBgcPzn:b27iwbb) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/48f0ff944d6f7372fcbb744577f235082f8e7f5c/test/touch.html#L47)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

The same observation here about the `{} call` usage that I did in uploader
</blockquote></details>

replaced with `touchEventInit.hasOwnProperty(touchEventInit)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: 1 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/touch.html, line 47 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44#-KYrP2OwFu3-Pxl3RFXg:-KYsBGL7FJCyvLwlk4K7:b-np37ju) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/48f0ff944d6f7372fcbb744577f235082f8e7f5c/test/touch.html#L47)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

replaced with `touchEventInit.hasOwnProperty(touchEventInit)`
</blockquote></details>

It is completely redundant here. Maybe remove the entire line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44)*

**Comment by limonte** [comment]
Review status: 1 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/touch.html, line 47 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44#-KYrP2OwFu3-Pxl3RFXg:-KYsSPtZhD1ECWyvr7ki:b-43l7ql) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/48f0ff944d6f7372fcbb744577f235082f8e7f5c/test/touch.html#L47)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

It is completely redundant here. Maybe remove the entire line?
</blockquote></details>

there's http://eslint.org/docs/rules/guard-for-in in our linter config. If you think that rule is redundant I'll remove it from the config.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44)*

**Comment by platosha** [comment]
Review status: 1 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/touch.html, line 47 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44#-KYrP2OwFu3-Pxl3RFXg:-KYsUFlBErDZdT3-Uy21:b-wllty7) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/48f0ff944d6f7372fcbb744577f235082f8e7f5c/test/touch.html#L47)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

there's http://eslint.org/docs/rules/guard-for-in in our linter config. If you think that rule is redundant I'll remove it from the config.
</blockquote></details>

Don’t have an opinion about the linter rule myself.

After discussing with @tomivirkki and @saulis we concluded that this requirement from the linter is redundant for us.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44)*

**Comment by limonte** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/touch.html, line 47 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44#-KYrP2OwFu3-Pxl3RFXg:-KYsXcY0IBVvAbJE6YIM:b-lmnxm7) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/48f0ff944d6f7372fcbb744577f235082f8e7f5c/test/touch.html#L47)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Don’t have an opinion about the linter rule myself.

After discussing with @tomivirkki and @saulis we concluded that this requirement from the linter is redundant for us.
</blockquote></details>

`guard-for-in` rule was removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44)*

**Comment by manolo** [comment]
:lgtm_strong: 

---

Reviewed 14 of 15 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44#-:-KYw4q4HBwYxv5QtagpW:b-uwkowd)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 54 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44#-KYwJHo4Joo2at5btwTv:-KYwJHo5lrGy6ehaUIeX:b-iu1lls) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/76262281602055295c36d02266d9c51be0799a4f/README.md#L54)):*
> ```Markdown
> ## Contributing
> 
> 1. Fork the `<vaadin-context-menu>` repository.
> ```

I feel like we should use better the clone word here instead the fork. The user does not need to fork if he wants to modify the element, only when he wants to send a PR.
So, probably the workflow is clone -> run demos -> run tests -> modify (coding style) - > and I miss a send a PR section (need to fork here) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 54 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44#-KYwJHo4Joo2at5btwTv:-KYwLakhMvcKUPkAHrRv:b4tys2i) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/76262281602055295c36d02266d9c51be0799a4f/README.md#L54)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I feel like we should use better the clone word here instead the fork. The user does not need to fork if he wants to modify the element, only when he wants to send a PR.
So, probably the workflow is clone -> run demos -> run tests -> modify (coding style) - > and I miss a send a PR section (need to fork here) 
</blockquote></details>

This is the **contributing** guide, so the user in most cases wants to send a PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 54 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44#-KYwJHo4Joo2at5btwTv:-KYwQLzA_J1ee6e6AcC3:b-cuwtm8) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/76262281602055295c36d02266d9c51be0799a4f/README.md#L54)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

This is the **contributing** guide, so the user in most cases wants to send a PR.
</blockquote></details>

which guide do you mean?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 54 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44#-KYwJHo4Joo2at5btwTv:-KYwUDoJcjd_rS7NJzm_:b-chjlym) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/76262281602055295c36d02266d9c51be0799a4f/README.md#L54)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

which guide do you mean?
</blockquote></details>

https://i.imgur.com/TujepKc.png

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/44)*

**Pull request merged**
