### PR TITLE
Include a static getter for the element version

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/117)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[gulpfile.js, line 66 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/117#-KyzASmXEtUTiGsIgCVb:-KyzASmXEtUTiGsIgCVc:b-7q2osn) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/cc0c587162ca79a9bb9a277681efdd51e638d1fc/gulpfile.js#L66)):*
> ```JavaScript
>   // Assumes that the old version is in package.json and the new version in the `npm_package_version` environment variable
>   const oldversion = require('./package.json').version;
> var find = require('gulp-find');
> ```

The script here has failed :-( 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/117)*

**Comment by Artur-** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[gulpfile.js, line 66 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/117#-KyzASmXEtUTiGsIgCVb:-KyzGw3iHy48PNCN24OJ:b-886gsx) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/cc0c587162ca79a9bb9a277681efdd51e638d1fc/gulpfile.js#L66)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

The script here has failed :-( 
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/117)*

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-context-menu.html, line 215 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/117#-KyzHd3bamogv8p7MrQ2:-KyzHd3bamogv8p7MrQ3:b1c2y87) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/cc0c587162ca79a9bb9a277681efdd51e638d1fc/vaadin-context-menu.html#L215)):*
> ```HTML
>         }
> 
>         
> ```

nit: spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/117)*

**Comment by manolo** [comment]
:lgtm_strong: 

---

Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/117#-:-KyzLysHC6MH8oOSW-E_:b-uwkowd)*

**Pull request merged**
