### PR TITLE
2.0 preview

### PR DESCRIPTION
**Pull request by manolo**
Connected to #70

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/76)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/.eslintrc.json, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-KjmRQ2KlRohn3G8EsK2:-KjmRQ2KlRohn3G8EsK3:b-5xug1f) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/6e2c769e2525eef7665b82b533e4cc83b62a214c/demo/.eslintrc.json#L9)):*
> ```JSON
>     "getItems": false,
>     "getNewItem": false,
>     "getRandomItems": false
> ```

not used anywhere else

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-:-KjmRi-zfs2Y0Li29v09:bnfp4nl)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[bower.json, line 26 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-Kjq9cbidI2M-wnBJZWf:-Kjq9cbidI2M-wnBJZWg:b-ual8nw) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/190dbeb9b1b7318756356f07502175b0c5089992/bower.json#L26)):*
> ```JSON
>     "iron-overlay-behavior": "^1.8.6",
>     "iron-media-query": "^1.0.8",
>     "paper-styles": "^1.1.5"
> ```

Is `paper-styles` removed intentionally? It's still used in `demo/common.html`

---

*[vaadin-context-menu-overlay.html, line 99 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-Kjr75S1QBR4J7R2tV06:-Kjr75S2ukoZyy2FGWSq:b8i593s) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/6e2c769e2525eef7665b82b533e4cc83b62a214c/vaadin-context-menu-overlay.html#L99)):*
> ```HTML
>       },
> 
>       _positionChanged: function(x, y) {
> ```

this should have `if ( x === undefined || y === undefined) { return; }`

---

*[vaadin-contextmenu-event.html, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-KjqArnvuOZOlznNEH3z:-KjqArnvuOZOlznNEH4-:b-6k1eo1) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/6e2c769e2525eef7665b82b533e4cc83b62a214c/vaadin-contextmenu-event.html#L12)):*
> ```HTML
>   if (Polymer.Element) {
>     // 2.x needs this legacy import
>     Polymer.Base.importHref('../../polymer/lib/utils/gestures.html');
> ```

Are you sure? Looks to me `polymer.html` imports `lib/legacy/legacy-element-mixin.html` which imports `lib/mixins/gesture-event-listeners.html` which imports `lib/utils/gestures.html`  ?

---

*[vaadin-contextmenu-event.html, line 54 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-KjqBPXKnqAwqIAz5Gee:-KjqBPXKnqAwqIAz5Gef:b-nfr7js) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/6e2c769e2525eef7665b82b533e4cc83b62a214c/vaadin-contextmenu-event.html#L54)):*
> ```HTML
>         };
> 
>         this._timerId = setTimeout(function() {
> ```

`setTimeout` isn't the same thing as `Debounce`. You can use `Polymer.Debouncer.Debounce` in Polymer 2.

---

*[vaadin-contextmenu-event.html, line 89 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-KjqBwQSVYWHMwG-sDPT:-KjqBhg1MB0UJ6eNs6oz:bioy96m) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/6e2c769e2525eef7665b82b533e4cc83b62a214c/vaadin-contextmenu-event.html#L89)):*
> ```HTML
>       fire: function(target, x, y) {
>         // 2.0 has moved _fire method to private API
>         (Polymer.Gestures.fire || Polymer.Gestures._fire)(target, 'vaadin-contextmenu', {
> ```

As a comment, we should use `dispatchEvent(...)` once we go to pure 2.0.

---

*[test/touch.html, line 159 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-Kjr7e-HdFg_638sxv8x:-Kjr7e-HdFg_638sxv8y:b-7kvxhc) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/6e2c769e2525eef7665b82b533e4cc83b62a214c/test/touch.html#L159)):*
> ```HTML
>           makeSoloTouchEvent('touchstart', xy, target);
> 
>           menu.async(function() {
> ```

Instead of using `async` we could listen for `iron-overlay-opened` and drop the 600ms timeout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76)*

**Comment by tomivirkki** [comment]
Needs `bower_components*` and `bower-*` in .gitignore. The file could further be aligned with that of `<vaadin-upload>`.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-:-KjrDcq44MKGqEbpOUrH:b-7wg0ro)*

**Comment by manolo** [comment]
Review status: 19 of 23 files reviewed at latest revision, 5 unresolved discussions.

---

*[bower.json, line 26 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-Kjq9cbidI2M-wnBJZWf:-KjrPc9Pqc8abUm7ORmY:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/190dbeb9b1b7318756356f07502175b0c5089992/bower.json#L26)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Is `paper-styles` removed intentionally? It's still used in `demo/common.html`
</blockquote></details>

Done.

---

*[vaadin-context-menu-overlay.html, line 99 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-Kjr75S1QBR4J7R2tV06:-KjrKlcrvcZ6L_TBUNV5:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/6e2c769e2525eef7665b82b533e4cc83b62a214c/vaadin-context-menu-overlay.html#L99)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

this should have `if ( x === undefined || y === undefined) { return; }`
</blockquote></details>

Done.

---

*[vaadin-contextmenu-event.html, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-KjqArnvuOZOlznNEH3z:-KjrJxreJ9qSRTAXTG4S:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/6e2c769e2525eef7665b82b533e4cc83b62a214c/vaadin-contextmenu-event.html#L12)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Are you sure? Looks to me `polymer.html` imports `lib/legacy/legacy-element-mixin.html` which imports `lib/mixins/gesture-event-listeners.html` which imports `lib/utils/gestures.html`  ?
</blockquote></details>

Done.

---

*[test/touch.html, line 159 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-Kjr7e-HdFg_638sxv8x:-KjrMVN9hrz8NwsHX2aS:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/6e2c769e2525eef7665b82b533e4cc83b62a214c/test/touch.html#L159)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Instead of using `async` we could listen for `iron-overlay-opened` and drop the 600ms timeout.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76)*

**Comment by Saulis** [comment]
`WebComponentsReady` need to be added in one of demos, otherwise :lgtm: 

---

Review status: 19 of 24 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/advanced.html, line 92 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-KjvD4p6-UcTz5bX_Mjd:-KjvD4p7ESvBFcq8cALC:bwetfzm) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/6e2c769e2525eef7665b82b533e4cc83b62a214c/demo/advanced.html#L92)):*
> ```HTML
> 
>           <script>
>             Polymer({
> ```

This script needs to be wrapped in a `document.addEventListener('WebComponentsReady', ...)` 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-:-KjvDBmHeardsR3c7RSN:b-94bp22)*

**Comment by Saulis** [comment]
Reviewed 19 of 23 files at r1, 5 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/advanced.html, line 92 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-KjvD4p6-UcTz5bX_Mjd:-KjvcWkaK_3kWUvSlv5y:bqmjwcz) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/6e2c769e2525eef7665b82b533e4cc83b62a214c/demo/advanced.html#L92)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

This script needs to be wrapped in a `document.addEventListener('WebComponentsReady', ...)` 
</blockquote></details>

Added.

---

*[demo/.eslintrc.json, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-KjmRQ2KlRohn3G8EsK2:-KjvcO4xELsouFdrO00q:brpmqc3) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/6e2c769e2525eef7665b82b533e4cc83b62a214c/demo/.eslintrc.json#L9)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

not used anywhere else
</blockquote></details>

removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76)*

**Comment by tomivirkki** [comment]
*[bower.json, line 40 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-Kjve3BzYpLQ_cCBMl2V:-Kjve3BzYpLQ_cCBMl2W:b6to71o) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0187a2034c2d084d41be650227ddca13f50adc0a/bower.json#L40)):*
> ```JSON
>     "web-component-tester": "^6.0.0"
>   },
>   "variants": {
> ```

There's unnecessary resolutions in the variant. This will work here also https://github.com/vaadin/vaadin-upload/blob/master/bower.json#L51

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76)*

**Comment by tomivirkki** [comment]
*[test/common.js, line 2 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-KjvfOohhoBusCIXO5BB:-KjvfOohhoBusCIXO5BC:b-k7yp3o) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0187a2034c2d084d41be650227ddca13f50adc0a/test/common.js#L2)):*
> ```JavaScript
> 
> window.listenForEvent = function(elem, type, callback) {
> ```

`listenForEvent` doesn't describe well what this function does. Rename to `listenOnce` (to align with https://github.com/vaadin/vaadin-grid/blob/master/test/helpers.html#L61)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76)*

**Comment by manolo** [comment]
Review status: 17 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

*[bower.json, line 40 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-Kjve3BzYpLQ_cCBMl2V:-KjvplE1HXMp7pAh_b-7:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0187a2034c2d084d41be650227ddca13f50adc0a/bower.json#L40)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

There's unnecessary resolutions in the variant. This will work here also https://github.com/vaadin/vaadin-upload/blob/master/bower.json#L51
</blockquote></details>

Done.

---

*[test/common.js, line 2 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-KjvfOohhoBusCIXO5BB:-KjvobFx-kl6oSyihL0e:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/0187a2034c2d084d41be650227ddca13f50adc0a/test/common.js#L2)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

`listenForEvent` doesn't describe well what this function does. Rename to `listenOnce` (to align with https://github.com/vaadin/vaadin-grid/blob/master/test/helpers.html#L61)
</blockquote></details>

Done.

---

*[demo/.eslintrc.json, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-KjmRQ2KlRohn3G8EsK2:-KjvocbzqRfiOnc0xwkl:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/6e2c769e2525eef7665b82b533e4cc83b62a214c/demo/.eslintrc.json#L9)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

removed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-:-KjxeYe-v_sIw7VSoDpR:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 17 of 23 files at r1, 5 of 5 files at r2, 2 of 2 files at r3, 7 of 7 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/76#-:-Kk9s10c7IHlLPrnFwmU:bnfp4nl)*

**Pull request merged**
