### PR TITLE
Prevent touchend in capture mode

### LINKED ISSUE #78: Overlay doesn’t stay open
I have the same issue as #71 in Polymer 2.0 and Chrome 58 with the following example.
```html
<vaadin-context-menu>
	<template>
		<paper-listbox>
			<paper-item>First menu item</paper-item>
			<paper-item>Second menu item</paper-item>
		</paper-listbox>
	</template>

	<paper-listbox>
		<paper-item>This item has the context menu provided in the above template.</paper-item>
		<paper-item>Another item with the context menu.</paper-item>
	</paper-listbox>
</vaadin-context-menu>
```

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #78

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/79)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-contextmenu-event.html, line 61 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/79#-KlJ0oLXpK-NJblDQ63c:-KlJ0oLXpK-NJblDQ63d:b-q855um) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/4a3d27d344875ccbf75596134f7610846c2971f9/vaadin-contextmenu-event.html#L61)):*
> ```HTML
>             // needed to prevent any 'tap' gesture events from firing
>             // which could potentially cancel/close the overlay.
>             this._preventNextTouchend();
> ```

It seems there is an API for that:

```javascript
Polymer.Gestures.prevent('tap');
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/79)*

**Comment by samiheikki** [comment]
lgtm but `_preventNextTouchEnd` could be changed to use Polymer Gestures if it works.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/79#-:-KlMmKVNKVS6jDA1acP2:bryg28c)*

**Comment by Saulis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-contextmenu-event.html, line 61 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/79#-KlJ0oLXpK-NJblDQ63c:-KlNJL-ilPzFveii3SLK:bgv5n6k) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/4a3d27d344875ccbf75596134f7610846c2971f9/vaadin-contextmenu-event.html#L61)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

It seems there is an API for that:

```javascript
Polymer.Gestures.prevent('tap');
```
</blockquote></details>

Nicceeeee!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/79)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/79#-:-KlNNrSdXARSISdY8GOx:bnfp4nl)*

**Comment by platosha** [comment]
:warning: failing build. Needs some fix for the test now.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/79#-:-KlNNxy2twLAHzPjBhzE:b-nf9ccd)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/79#-:-KlO7OJJlynZVnMxgr-K:bnfp4nl)*

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/79#-:-KlOLqEaSOejBWibJhoE:bnfp4nl)*

**Pull request merged**
