### PR TITLE
Adapt demos to new vaadin site

### PR DESCRIPTION
**Pull request by manolo**
Connected to vaadin/components-team-tasks#273

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/104)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 7 of 10 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/104#-:-KuTF9Tu-Enm1BixOWFZ:bnfp4nl)*

**Comment by limonte** [comment]
This PR is not properly rebased.

**Comment by manolo** [comment]
@limonte  Rebased

---

Review status: 9 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/104#-:-KuTTKa5RkcmRe5AhMVt:b-826u4l)*

**Comment by tomivirkki** [comment]
*[bower.json, line 45 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/104#-KuTX3wXr-bvXtroFw78:-KuTX3wXr-bvXtroFw79:b-satgjc) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/a461bd9ba98f6f0a994a5497f8c4538d0951a550/bower.json#L45)):*
> ```JSON
>     "vaadin-demo-helpers": "vaadin/vaadin-demo-helpers"
>   },
>   "resolutions": {
> ```

This empty resolutions block is quite annoying as it gets removed by `polymer install` automatically

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/104)*

**Comment by manolo** [comment]
Review status: 8 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[bower.json, line 45 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/104#-KuTX3wXr-bvXtroFw78:-KuTXamNWwTnd9Lifk02:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/a461bd9ba98f6f0a994a5497f8c4538d0951a550/bower.json#L45)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This empty resolutions block is quite annoying as it gets removed by `polymer install` automatically
</blockquote></details>

Done.

---

*[vaadin-context-menu.html, line 19 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/104#-KuTW59ivCUHQbG12X8T:-KuTXcQ_aqx95j_jglNq:b-n28vnq) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/a461bd9ba98f6f0a994a5497f8c4538d0951a550/vaadin-context-menu.html#L19)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

What are these and how do they relate to the PR?
</blockquote></details>

They are partially related with the issue in https://gitlab.vaadin.com/vaadincom/webpage/issues/1754 .

If you remove this fix, the site looks like  in this screenshot 



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/104)*

**Comment by tomivirkki** [comment]
*[vaadin-context-menu.html, line 19 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/104#-KuTW59ivCUHQbG12X8T:-KuT_WN_bzaFgLNvFrrU:bi2nzo8) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/a461bd9ba98f6f0a994a5497f8c4538d0951a550/vaadin-context-menu.html#L19)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

They are partially related with the issue in https://gitlab.vaadin.com/vaadincom/webpage/issues/1754 .

If you remove this fix, the site looks like  in this screenshot 




</blockquote></details>

I don't think this is the proper fix. @anton? There's some outdated dependency causing this (valo/overlay/contextmenu)... You can try this locally and the overlay _should_ span to bottom and right. Rest is just about styling.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/104)*

**Comment by platosha** [comment]
Review status: 8 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-context-menu.html, line 19 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/104#-KuTW59ivCUHQbG12X8T:-KuTpFjNe3ESkpj8xzpA:b-z4vdoo) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/a461bd9ba98f6f0a994a5497f8c4538d0951a550/vaadin-context-menu.html#L19)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I don't think this is the proper fix. @anton? There's some outdated dependency causing this (valo/overlay/contextmenu)... You can try this locally and the overlay _should_ span to bottom and right. Rest is just about styling.
</blockquote></details>

This must be fixed elsewhere. Probably the valo theme should be updated/fixed. 

Otherwise, this workaround here will break scrolling for long menus for everybody (beta-blocking bug).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/104)*

**Comment by tomivirkki** [comment]
*[vaadin-context-menu.html, line 19 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/104#-KuTW59ivCUHQbG12X8T:-KuTqkVzlK4UP3Qu8w6n:bwvyox4) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/a461bd9ba98f6f0a994a5497f8c4538d0951a550/vaadin-context-menu.html#L19)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

This must be fixed elsewhere. Probably the valo theme should be updated/fixed. 

Otherwise, this workaround here will break scrolling for long menus for everybody (beta-blocking bug).
</blockquote></details>

Reverted

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/104)*

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r9.
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/104)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 6 of 10 files at r2, 2 of 2 files at r5, 2 of 2 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/104#-:-KuTt0mBLS8jTtWw3Y9I:bnfp4nl)*

**Pull request merged**
