### PR TITLE
Fix css

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/16)

### CODE REVIEW

**Comment by tehapo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demo/advanced.html, line 109 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KS79Uvp4Nbek19-81mU:-KS79Uvqp9eC_hZjtVnu:b-eunajk) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/ed677fa3f5cd7f709fcfc625e2339bb2accee06b/demo/advanced.html#L109)):*
> ```HTML
>             _selectedChanged: function() {
>               for (var i = 0; this.columns && i < this.columns.length; i++) {
>                 this.columns[i].hidden = !this.selectedValues.includes(i);
> ```

The `includes` method is not available in IE11. That's why my previous PR changed this to use `indexOf`instead.

---

*[demo/advanced.html, line 111 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KS79qw3j7QjLJqJdwOt:-KS79qw4MxqJxyfnxNgA:b-v4cisy) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/ed677fa3f5cd7f709fcfc625e2339bb2accee06b/demo/advanced.html#L111)):*
> ```HTML
>                 this.columns[i].hidden = !this.selectedValues.includes(i);
>               }
>             },
> ```

Also here is an unnecessary comma that I just removed in my PR. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by manolo** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/advanced.html, line 109 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KS79Uvp4Nbek19-81mU:-KSANflsJDMPmSRprXH5:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/ed677fa3f5cd7f709fcfc625e2339bb2accee06b/demo/advanced.html#L109)):*
<details><summary><i>Previously, tehapo (Teemu Pöntelin) wrote…</i></summary>
> The `includes` method is not available in IE11. That's why my previous PR changed this to use `indexOf`instead.
</details>
Done.

---

*[demo/advanced.html, line 111 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KS79qw3j7QjLJqJdwOt:-KSANgMzAjtQnOXBzjPt:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/ed677fa3f5cd7f709fcfc625e2339bb2accee06b/demo/advanced.html#L111)):*
<details><summary><i>Previously, tehapo (Teemu Pöntelin) wrote…</i></summary>
> Also here is an unnecessary comma that I just removed in my PR. :)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by Saulis** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-context-menu.html, line 25 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KSAdLPPcTGRjbK5pLrh:-KSAdLPPcTGRjbK5pLri:b-28wek8) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/e7679c3206e851b8880cac5ddb6958b9edc5f02b/vaadin-context-menu.html#L25)):*
> ```HTML
>       }
> 
>       vaadin-context-menu-overlay {
> ```

Have you checked if the styles inside `vaadin-context-menu-overlay.html` Work correctly? Especially in phones?

I guess `.dropdown-content` should have `width: 100%` after this change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by tehapo** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by manolo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-context-menu.html, line 25 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KSAdLPPcTGRjbK5pLrh:-KSFdoXCGON9wszwN7vn:bx9lbta) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/e7679c3206e851b8880cac5ddb6958b9edc5f02b/vaadin-context-menu.html#L25)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Have you checked if the styles inside `vaadin-context-menu-overlay.html` Work correctly? Especially in phones?
> 
> I guess `.dropdown-content` should have `width: 100%` after this change?
</details>
Fixed styles in the component.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by Saulis** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-context-menu-overlay.html, line 16 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KSG4wS-GsO1lpmxsGFL:-KSG4wS-GsO1lpmxsGFM:b-qce7vd) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/fd88423073d15b6e376a03dbb7815edc201318dd/vaadin-context-menu-overlay.html#L16)):*
> ```HTML
> 
>       :host([desktop]) {
>         position: fixed;
> ```

What's the reason behind changing these all away from being `fixed` on mobile? Instead, styles should be fixed for non-desktop:

```css
      :host(:not([desktop])) {
        display: flex;
        justify-content: center;
        width: calc(100vw - 2 * 20px) !important;
        margin: 0px 20px;

        bottom: 20px;
        transform: none !important;
        top: auto !important;
      }

```

seems to work just fine for me in `vaadin-context-menu-overlay.html` (remember to set `width: 100%` for `.dropdown-content`

---

*[vaadin-context-menu.html, line 28 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KSG4WZk9Fc8OjitE7VS:-KSG4WZlSF_RQnLtgXJM:b-z029qr) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/fd88423073d15b6e376a03dbb7815edc201318dd/vaadin-context-menu.html#L28)):*
> ```HTML
>         width: calc(64px * 4);
>         background: var(--primary-background-color, #ffffff);
>         overflow: scroll;
> ```

`overflow: auto` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by manolo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-context-menu-overlay.html, line 16 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KSG4wS-GsO1lpmxsGFL:-KSG6lFlRdIh3vV4hqzH:bkssae) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/fd88423073d15b6e376a03dbb7815edc201318dd/vaadin-context-menu-overlay.html#L16)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> What's the reason behind changing these all away from being `fixed` on mobile? Instead, styles should be fixed for non-desktop:
> 
> ```css
>       :host(:not([desktop])) {
>         display: flex;
>         justify-content: center;
>         width: calc(100vw - 2 * 20px) !important;
>         margin: 0px 20px;
> 
>         bottom: 20px;
>         transform: none !important;
>         top: auto !important;
>       }
> 
> ```
> 
> seems to work just fine for me in `vaadin-context-menu-overlay.html` (remember to set `width: 100%` for `.dropdown-content`
</details>
`transform: none` does not work when we style the `vaadin-context-menu-overlay` instead of the `.overlay-content`, so the best is not to do any transformation in mobile at all in code, and leave the component to center the content appropriately. 

Also adding justification to items makes the user have to override that if he want a different layout.
We don't need to set 100% for the .dropdown-content.

This current css works perfectly in mobile, do you see any issue?

---

*[vaadin-context-menu.html, line 28 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KSG4WZk9Fc8OjitE7VS:-KSG6McMA958x6hvvzkD:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/fd88423073d15b6e376a03dbb7815edc201318dd/vaadin-context-menu.html#L28)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> `overflow: auto` ?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by manolo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-context-menu-overlay.html, line 16 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KSG4wS-GsO1lpmxsGFL:-KSG9ocOl1ubo6Ni-JvD:b-kasrts) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/fd88423073d15b6e376a03dbb7815edc201318dd/vaadin-context-menu-overlay.html#L16)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> `transform: none` does not work when we style the `vaadin-context-menu-overlay` instead of the `.overlay-content`, so the best is not to do any transformation in mobile at all in code, and leave the component to center the content appropriately. 
> 
> Also adding justification to items makes the user have to override that if he want a different layout.
> We don't need to set 100% for the .dropdown-content.
> 
> This current css works perfectly in mobile, do you see any issue?
</details>
Note that setting .dropdown-content to 100% prevents it growing when items width is larger than the drop-down width. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by manolo** [comment]
I split the part of fixing IE11 demo to a separated PR

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-:-KSKiZc_KWD55az7ZV31:b-vukgsa)*

**Comment by Saulis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-context-menu-overlay.html, line 16 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KSG4wS-GsO1lpmxsGFL:-KSKwr5p5h7PwoDSH2Ds:bo2cav1) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/fd88423073d15b6e376a03dbb7815edc201318dd/vaadin-context-menu-overlay.html#L16)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Note that setting .dropdown-content to 100% prevents it growing when items width is larger than the drop-down width. 
</details>
I think there's a misunderstanding, `transform: none` works just fine in mobile, it just needs to have correct widths for the overlay and dropdown content. Problem in this case is that the explicit width from the overlay is overriding the `100vw` width in mobile mode. I suggest we remove the explicit width altogether, since the width should actually be determined by the overlay contents and the user can use the new mixin to override that. Same goes with setting `overflow`, I don't think anymore we should have a default value for that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-context-menu-overlay.html, line 16 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KSG4wS-GsO1lpmxsGFL:-KSL7TBcPAgyusrzNIxL:b-xwkkjx) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/fd88423073d15b6e376a03dbb7815edc201318dd/vaadin-context-menu-overlay.html#L16)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> I think there's a misunderstanding, `transform: none` works just fine in mobile, it just needs to have correct widths for the overlay and dropdown content. Problem in this case is that the explicit width from the overlay is overriding the `100vw` width in mobile mode. I suggest we remove the explicit width altogether, since the width should actually be determined by the overlay contents and the user can use the new mixin to override that. Same goes with setting `overflow`, I don't think anymore we should have a default value for that.
</details>
Why do you need `transform: none` if we do not do transformation in mobile ? I think the code is more readable not setting the transformation in code that setting it and depending on a css rule for not applying it.

The width in overlay was set because of the MD specification, but we can remove it, ask @platosha 

Right now if you remove the `overlay: auto` I set in this patch, you cannot scroll content. It's something that the user has to do specifically?, well IMO since the overlay computes certain size restrictions  depending on the context, I guess the safer is to leave the overlay auto by default so as scroll works without the user having to bother about. He can override it with the mixin though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-context-menu-overlay.html, line 16 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KSG4wS-GsO1lpmxsGFL:-KSL8rNRDeVdQICq1wF_:b-tht79m) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/fd88423073d15b6e376a03dbb7815edc201318dd/vaadin-context-menu-overlay.html#L16)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Why do you need `transform: none` if we do not do transformation in mobile ? I think the code is more readable not setting the transformation in code that setting it and depending on a css rule for not applying it.
> 
> The width in overlay was set because of the MD specification, but we can remove it, ask @platosha 
> 
> Right now if you remove the `overlay: auto` I set in this patch, you cannot scroll content. It's something that the user has to do specifically?, well IMO since the overlay computes certain size restrictions  depending on the context, I guess the safer is to leave the overlay auto by default so as scroll works without the user having to bother about. He can override it with the mixin though.
</details>
I meant `overflow: auto`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by manolo** [comment]
Based on #21 we might remove certain css props like `width: calc(64px * 4);`. I think also we don't need any margin or text justify etc.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-:-KS_Q80VWsOzAA8YqXhk:bd9lpuv)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-context-menu.html, line 30 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KSaREqoJ5ljpL23LfNU:-KSaREqp4B1JnQC4OSkS:b-y9hxrb) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/d15fc625d423f737ca4d30b97c26c8add17c57cb/vaadin-context-menu.html#L30)):*
> ```HTML
> 
>       .dropdown-content {
>         overflow: auto;
> ```

I feel that this should be in the vaadin-context-menu-overlay, so as the user can override it, but that breaks the padding approach.
So I'm ok if we either move the @apply styles to this section, or we have another mixin for it.

Also I think we should add a `display:flex ` or another trick so as if we set `paper-item: {width: 600px}` and ` `paper-menu: border: solid 2px blue;` the border rounds all the items

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by tomivirkki** [comment]
*[vaadin-context-menu.html, line 30 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KSaREqoJ5ljpL23LfNU:-KSaheAX5dHyxq2zPMBe:b-sdg1r8) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/d15fc625d423f737ca4d30b97c26c8add17c57cb/vaadin-context-menu.html#L30)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I feel that this should be in the vaadin-context-menu-overlay, so as the user can override it, but that breaks the padding approach.
> So I'm ok if we either move the @apply styles to this section, or we have another mixin for it.
> 
> Also I think we should add a `display:flex ` or another trick so as if we set `paper-item: {width: 600px}` and ` `paper-menu: border: solid 2px blue;` the border rounds all the items
</details>
Iron-dropdown doesn't provide a mixin for overriding the value and I don't think we should either (https://github.com/PolymerElements/iron-dropdown/blob/master/iron-dropdown.html#L54). Especially since we won't need it for vaadin-context-menu.

If a user really for some reason needs a non-scrolling container around the content, he can for example wrap it inside one right in the light dom.

You can fix your blue border issue by adding box-sizing: border-box; to the menu. It's not vaadin-combo-box's (or the overlay's) responsibility to fix that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[vaadin-context-menu.html, line 30 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KSaREqoJ5ljpL23LfNU:-KSamc8-Vy_40co2dvv6:bph2l83) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/d15fc625d423f737ca4d30b97c26c8add17c57cb/vaadin-context-menu.html#L30)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Iron-dropdown doesn't provide a mixin for overriding the value and I don't think we should either (https://github.com/PolymerElements/iron-dropdown/blob/master/iron-dropdown.html#L54). Especially since we won't need it for vaadin-context-menu.
> 
> If a user really for some reason needs a non-scrolling container around the content, he can for example wrap it inside one right in the light dom.
> 
> You can fix your blue border issue by adding box-sizing: border-box; to the menu. It's not vaadin-combo-box's (or the overlay's) responsibility to fix that.
</details>
iron-dropdown does not modifies any property of the .dropdown-content, there is no  need of having a mixin there.

Related with the border, I think we are referring to different issues. What I meant is that menu container should cover all item sizes, like it is shown in http://g.recordit.co/IENrSndFpP.gif versus the current behaviour in http://g.recordit.co/oOnWHwNo6u.gif 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by tomivirkki** [comment]
*[vaadin-context-menu.html, line 30 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KSaREqoJ5ljpL23LfNU:-KSawHjdUAfUwddaK3bE:b-jkkuur) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/d15fc625d423f737ca4d30b97c26c8add17c57cb/vaadin-context-menu.html#L30)):*
> iron-dropdown does not modifies any property of the .dropdown-content, there is no  need of having a mixin there.

Sure it does. Did you open the link I added?

About the border thing again: If you want it to scroll like that (like in the latter gif) just set the 600px width to the paper-menu, not the paper-items.

We still don't know about the details of the contained cascading menu we'll implement later so we should just stick to defaults for now. We can add more stuff later when needed. No need to rush in adding stuff beforehand based on assumptions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by tomivirkki** [comment]
*[vaadin-context-menu.html, line 30 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KSaREqoJ5ljpL23LfNU:-KSbAFa1NgGQhjF1CnPC:bfftn1m) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/d15fc625d423f737ca4d30b97c26c8add17c57cb/vaadin-context-menu.html#L30)):*
> iron-dropdown does not modifies any property of the .dropdown-content, there is no need of having a mixin there.

Ah, the internal dropdown-content element isn't visible outside, added the mixin

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by manolo** [comment]
Travis tests related with mobile seem failing

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[vaadin-context-menu.html, line 30 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KSaREqoJ5ljpL23LfNU:-KSe85FgLp6PnCuxbltg:borndwf) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/d15fc625d423f737ca4d30b97c26c8add17c57cb/vaadin-context-menu.html#L30)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> > iron-dropdown does not modifies any property of the .dropdown-content, there is no need of having a mixin there.
> 
> Ah, the internal dropdown-content element isn't visible outside, added the mixin
</details>
Exactly, each element that we use and modify should have a mixin, I would rather not maintain more mixins.

Related to the horizontal scrolling, I wanted the containers grow with its content, obviously I can set the width to it, but not was my point.

Anyway not blocker issues, so the PR lgtm but travis tests fail.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-:-KSe8nZxLUe1TSfL3gFi:b-4qo0do)*

**Comment by manolo** [comment]
:lgtm: 

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-:-KSeTzApiBujwohWKpct:bg7igkv)*

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r5, 1 of 1 files at r8.
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by manolo** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-context-menu-overlay.html, line 16 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-KSG4wS-GsO1lpmxsGFL:-KSeU77gZMgClxZBt0bj:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/fd88423073d15b6e376a03dbb7815edc201318dd/vaadin-context-menu-overlay.html#L16)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I meant `overflow: auto`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r5, 1 of 2 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16#-:-KSeb4xppQUYAUMwv1aN:bnfp4nl)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 2 files at r5, 1 of 2 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/16)*

**Pull request merged**
