### PR TITLE
Make `opened` public and read-only

### PR DESCRIPTION
**Pull request by manolo**
Connected to #46

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/50)

### CODE REVIEW

**Comment by vaadin-marcus** [comment]
Why make `opened` read-only? I think it would be more consistent with paper elements if it was writeable (for instance https://elements.polymer-project.org/elements/paper-dialog-behavior, https://elements.polymer-project.org/elements/paper-menu-button)

**Comment by platosha** [comment]
@vaadin-marcus It is simply not enough information coming from just setting the opened flag to `true` in order to get a correct and consistently displayed context menu.

The main problem here on my mind is determining where should the context menu be positioned when it opens. When users open a context menu with a right mouse click, which is the basic use case, they expect to see it right under their cursor. Because of this, the `open` method requires an event argument to extract the coordinates from.

In addition, not only the position could change, but also the context data of the menu changes depending on where and when it was opened. For instance, when there is a list of some items in the content, and there is a context menu with “Remove” action, which should remove an item from the list. In the “Remove” click handler it should be possible to access the list item the menu was opened for, i. e., the menu opening event target. We have `target` and `detail` properties of the menu opening event exposed to the menu template bindings to support it.

**Comment by Saulis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-context-menu.html, line 38 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/50#-KZ1AeXaV3awgXLUAWT6:-KZ1AeXaV3awgXLUAWT7:b-prv75w) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/256ac29523212579c584571e02c37f163028789a/vaadin-context-menu.html#L38)):*
> ```HTML
> 
>     <content></content>
>     <vaadin-context-menu-overlay id="overlay" on-iron-overlay-opened="_onOverlayOpened" opened="{{_overlayOpened}}">
> ```

Rather than introducing a new property which just duplicates `opened`, I'd propose adding a `_onOverlayClosed` listener here which would call `this._setOpened(false)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/50)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-context-menu.html, line 38 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/50#-KZ1AeXaV3awgXLUAWT6:-KZ1CByP4QIppnKy6Eck:byy4f5o) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/256ac29523212579c584571e02c37f163028789a/vaadin-context-menu.html#L38)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Rather than introducing a new property which just duplicates `opened`, I'd propose adding a `_onOverlayClosed` listener here which would call `this._setOpened(false)`
</blockquote></details>

I already tried that at first, but breaks some tests that also listen for that property.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/50)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-context-menu.html, line 38 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/50#-KZ1AeXaV3awgXLUAWT6:-KZ1D84dZa_9Wge4bVJc:b1wcfk) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/256ac29523212579c584571e02c37f163028789a/vaadin-context-menu.html#L38)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I already tried that at first, but breaks some tests that also listen for that property.
</blockquote></details>

Anyway, Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/50)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/50#-:-KZ1E0eWb1_cNc7BIAVZ:bnfp4nl)*

**Pull request merged**
