### PR TITLE
Update the styling example

### PR DESCRIPTION
**Pull request by limonte**
Connected to https://github.com/vaadin/components-team-tasks/issues/347

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/151)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[demo/context-menu-basic-demos.html, line 35 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/151#-LAYJi_p0lqQ7-VAqVPO:-LAYJi_p0lqQ7-VAqVPP:b-214ulw) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/32a402ed1ffd27576e14e48505cedf14f923bcc0/demo/context-menu-basic-demos.html#L35)):*
> ```HTML
>           }
> 
>           vaadin-item:hover {
> ```

Don't change the font style on hover. Feels jumpy: https://www.dropbox.com/s/em3kbnwmzijfodc/Kapture%202018-04-20%20at%2016.50.13.gif?dl=0

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/151)*

**Comment by limonte** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/context-menu-basic-demos.html, line 35 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/151#-LAYJi_p0lqQ7-VAqVPO:-LAYMRAEAhxlzWAHWQO1:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/32a402ed1ffd27576e14e48505cedf14f923bcc0/demo/context-menu-basic-demos.html#L35)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Don't change the font style on hover. Feels jumpy: https://www.dropbox.com/s/em3kbnwmzijfodc/Kapture%202018-04-20%20at%2016.50.13.gif?dl=0
</blockquote></details>

done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/151)*

**Comment by tomivirkki** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/151)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-context-menu/151#-:-LAYOcpq5yaxIbyCxnCj:bnfp4nl)*

**Pull request merged**
