### PR TITLE
Pass touchstart as sourceEvent for long touch

### LINKED ISSUE #23: X and Y coordinates are missing when overlay is opened using iPad (long-touch event)

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #23

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/27)

### CODE REVIEW

**Comment by platosha** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-context-menu.html, line 225 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/27#-KU_x0GuzMz_GOPR5Ch5:-KU_x0GuzMz_GOPR5Ch6:bf18dmp) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b1276cf76c797e2fc3564814a8207da54292a85d/vaadin-context-menu.html#L225)):*
> ```HTML
> 
>       _getEventCoordinate: function(event, coordinate) {
>         var sourceEvent = event.detail && event.detail.sourceEvent;
> ```

Should we loop to unwrap even deeper `detail.sourceEvent` references here? For ex.:
- `<vaadin-grid>` fires `"detailed-vaadin-long-touch"` event,
- which has `detail.sourceEvent` of `"vaadin-long-touch"` event,
- which has the original `detail.sourceEvent` finally

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/27)*

**Comment by platosha** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-context-menu.html, line 225 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/27#-KU_x0GuzMz_GOPR5Ch5:-KU_yBpOC-IYOQ8OplwO:b2hm2vr) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b1276cf76c797e2fc3564814a8207da54292a85d/vaadin-context-menu.html#L225)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Should we loop to unwrap even deeper `detail.sourceEvent` references here? For ex.:
> - `<vaadin-grid>` fires `"detailed-vaadin-long-touch"` event,
> - which has `detail.sourceEvent` of `"vaadin-long-touch"` event,
> - which has the original `detail.sourceEvent` finally
</details>
If not, then we probably should revert to passing `x` and `y` in the detail of "vaadin-long-touch". Then:
- If we have detailed event here, we unwrap the `sourceEvent` once,
- Then we take `x` and `y` from detail of custom events, or take clientX from native mouse or touch events.

That would be coherent with Polymer’s gesture events API.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/27)*

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-context-menu.html, line 225 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/27#-KU_x0GuzMz_GOPR5Ch5:-KUpQLBVz0df_Xqju_Xx:b-cs54q) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/b1276cf76c797e2fc3564814a8207da54292a85d/vaadin-context-menu.html#L225)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> If not, then we probably should revert to passing `x` and `y` in the detail of "vaadin-long-touch". Then:
> - If we have detailed event here, we unwrap the `sourceEvent` once,
> - Then we take `x` and `y` from detail of custom events, or take clientX from native mouse or touch events.
> 
> That would be coherent with Polymer’s gesture events API.
> 
</details>
I would vote for reverting, makes it easier to also use custom events.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/27)*

**Comment by platosha** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-context-menu.html, line 224 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/27#-KUv9JnCVGUKOoRD-n_R:-KUv9JnCVGUKOoRD-n_S:b9pb6q5) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/28ca13545e87400ab8f9a8c3ffa08dd0397bd3fd/vaadin-context-menu.html#L224)):*
> ```HTML
>       },
> 
>       _getEventCoordinate: function(event, prop) {
> ```

Let `event` be `detailed-tap` here in this method. Then:

- `coordinate` is will be set to undefined: `detailed-tap` is not a mouse/touch event, it lacks `clientX`/`clientY`.

- `event.detail` is true
  - `sourceEvent` becomes `tap`
  - `coordinate` lookup from `sourceEvent` fails: source event `tap` is not a mouse/touch event
  - `coordinate` lookup from `event.detail` fails: `event.detail` is a detail from `detailed-tap`, it lacks `clientX`/`clientY` as well.

---

*[vaadin-context-menu.html, line 230 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/27#-KUv7MSzaOthlPvoUcgk:-KUv7MSzaOthlPvoUcgl:b-havoj5) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/28ca13545e87400ab8f9a8c3ffa08dd0397bd3fd/vaadin-context-menu.html#L230)):*
> ```HTML
>           var sourceEvent = event.detail.sourceEvent || event;
>           coordinate = sourceEvent.changedTouches ? sourceEvent.changedTouches[0][prop] : sourceEvent[prop] || coordinate;
>           coordinate = event.detail[prop] || coordinate;
> ```

I was thinking of taking `detail.x`, not `detail.clientX`, to be coherent with Polymer’s builtin gesture events, which have `x` and `y` in the detail.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/27)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-context-menu.html, line 224 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/27#-KUv9JnCVGUKOoRD-n_R:-KVPtUOQtis6K9prmgEl:b32w0x) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/28ca13545e87400ab8f9a8c3ffa08dd0397bd3fd/vaadin-context-menu.html#L224)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Let `event` be `detailed-tap` here in this method. Then:
> 
> - `coordinate` is will be set to undefined: `detailed-tap` is not a mouse/touch event, it lacks `clientX`/`clientY`.
> 
> - `event.detail` is true
>   - `sourceEvent` becomes `tap`
>   - `coordinate` lookup from `sourceEvent` fails: source event `tap` is not a mouse/touch event
>   - `coordinate` lookup from `event.detail` fails: `event.detail` is a detail from `detailed-tap`, it lacks `clientX`/`clientY` as well.
</details>
OK

---

*[vaadin-context-menu.html, line 230 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/27#-KUv7MSzaOthlPvoUcgk:-KVPtVX5UCHaWEhkDdrk:b32w0x) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/28ca13545e87400ab8f9a8c3ffa08dd0397bd3fd/vaadin-context-menu.html#L230)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> I was thinking of taking `detail.x`, not `detail.clientX`, to be coherent with Polymer’s builtin gesture events, which have `x` and `y` in the detail.
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/27#-:-KVPtmgxeFVuCBQScR9r:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/27#-:-KVQ5uW1ysaWczMDG9uI:bnfp4nl)*

**Pull request merged**
