### PR TITLE
Close previous context menu before opening the next one

### LINKED ISSUE #53: Context menu is not getting the right context on two right-clicks one after another

### PR DESCRIPTION
**Pull request by limonte**
Fixes #53

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/60)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-context-menu.html, line 223 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60#-KZzopDE6G-IXHFOHO5l:-KZzopDE6G-IXHFOHO5m:b-xae880) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/1ea59b0b60b353b560e61fbb282865cd3847b613/vaadin-context-menu.html#L223)):*
> ```HTML
>         '_contentTemplateChanged(_contentTemplate)',
>         '_openedChanged(opened)',
>         '_targetOrOpenOnChanged(listenOn, openOn, isAttached)'
> ```

What is the reason of removing this variable in the observer?

The author of this code wanted to be sure that the component is attached to the dom before running `_targetOrOpenOnChanged`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-context-menu.html, line 223 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60#-KZzopDE6G-IXHFOHO5l:-KZzq3m0jnf920-dtJ1Z:b-py439r) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/1ea59b0b60b353b560e61fbb282865cd3847b613/vaadin-context-menu.html#L223)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

What is the reason of removing this variable in the observer?

The author of this code wanted to be sure that the component is attached to the dom before running `_targetOrOpenOnChanged`.


</blockquote></details>

Oops, my bad. Reverted. Thanks for the explanation!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-context-menu.html, line 322 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60#-KZzs64eOEiN_JUheFbt:-KZzs64fvmvIt2QU1z4I:bos5spm) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/4359a33451de54d60c6ac80838d26eee6635e398/vaadin-context-menu.html#L322)):*
> ```HTML
> 
>             if (this.opened) {
>               this.close();
> ```

have you tried a solution without having to close the component, but updating it? there is a light blink 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60)*

**Comment by Saulis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-context-menu.html, line 322 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60#-KZzqkW_nlE0sg-sKZRp:-KZzqkW_nlE0sg-sKZRq:b-k5zuqc) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/dabc060dc7be2091990ff552b7c907969bdb0d8f/vaadin-context-menu.html#L322)):*
> ```HTML
> 
>             if (this.opened) {
>               this.close();
> ```

I'm guessing the reason why you added this `close()` here is that `_openedChanged` isn't called otherwise. Logic-wise, there should not be any need to close the overlay in between clicks.

Looking at the `openedChanged` observer, what we actually should do is just add a new observer: `_contextChanged(_context, _instance)` and move these from `_openedChanged` to there: 

```js
this._instance.detail = this._context.detail;
this._instance.target = this._context.target;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60)*

**Comment by Saulis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-context-menu.html, line 322 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60#-KZzqkW_nlE0sg-sKZRp:-KZztLw7X1mZYXRFQwsB:bw399sl) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/dabc060dc7be2091990ff552b7c907969bdb0d8f/vaadin-context-menu.html#L322)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I'm guessing the reason why you added this `close()` here is that `_openedChanged` isn't called otherwise. Logic-wise, there should not be any need to close the overlay in between clicks.

Looking at the `openedChanged` observer, what we actually should do is just add a new observer: `_contextChanged(_context, _instance)` and move these from `_openedChanged` to there: 

```js
this._instance.detail = this._context.detail;
this._instance.target = this._context.target;
```
</blockquote></details>

More precisely, setting the `instance.detail` and `instance.target` are the variables `[[detail]]` and `[[target]]` that end up inside the template.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60)*

**Comment by limonte** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-context-menu.html, line 322 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60#-KZzqkW_nlE0sg-sKZRp:-K_-s2WsqmylncQHsVCq:bf3maur) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/dabc060dc7be2091990ff552b7c907969bdb0d8f/vaadin-context-menu.html#L322)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

More precisely, setting the `instance.detail` and `instance.target` are the variables `[[detail]]` and `[[target]]` that end up inside the template.
</blockquote></details>

Done, thank you!

---

*[vaadin-context-menu.html, line 322 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60#-KZzs64eOEiN_JUheFbt:-K_-s4LnBtPa0nB3kn1J:bpg9aex) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/4359a33451de54d60c6ac80838d26eee6635e398/vaadin-context-menu.html#L322)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

have you tried a solution without having to close the component, but updating it? there is a light blink 
</blockquote></details>

Done with Sauli's approach

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-context-menu.html, line 223 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60#-K_0QedkbpwkBP8weAMY:-K_0QedkbpwkBP8weAMZ:b40j3e) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/a651d17a7e5ab0cdfa3205ab59757ba0bf5a2fcb/vaadin-context-menu.html#L223)):*
> ```HTML
>         '_contentTemplateChanged(_contentTemplate)',
>         '_openedChanged(opened)',
>         '_contextChanged(_context)',
> ```

I guess you have to observe for the _instance changes as well 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60)*

**Comment by Saulis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-context-menu.html, line 276 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60#-K_0hEHlQqQ36ALTCTKG:-K_0hEHlQqQ36ALTCTKH:b-9br83h) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/a651d17a7e5ab0cdfa3205ab59757ba0bf5a2fcb/vaadin-context-menu.html#L276)):*
> ```HTML
>           })[0];
> 
>           if (this._context && this._instance) {
> ```

This block should be removed since `_contextChanged` is run inside `open(e)` – which is the only place `opened` is set to true.

---

*[vaadin-context-menu.html, line 283 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60#-K_0ghJ2Ek92iFgv34RL:-K_0ghJ2Ek92iFgv34RM:b-cgsqvf) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/a651d17a7e5ab0cdfa3205ab59757ba0bf5a2fcb/vaadin-context-menu.html#L283)):*
> ```HTML
>       },
> 
>       _contextChanged: function(context) {
> ```

Like @manolo pointed out, we should add `instance` argument to this observer as well so that we don't need to check for the `this.opened` status at all. Currently the check is needed because `_instance` is set only after the overlay has been opened for the first time.

Just making sure if you didn't know this already: when using observer functions in Polymer (1.x), the observers will be triggered only after all the properties are set to something else than `undefined`. So they can be effectively used to reduce `if` clauses for checking `undefined` properties.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60)*

**Comment by limonte** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-context-menu.html, line 223 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60#-K_0QedkbpwkBP8weAMY:-K_3_hr4zaAY86qpIjg7:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/a651d17a7e5ab0cdfa3205ab59757ba0bf5a2fcb/vaadin-context-menu.html#L223)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I guess you have to observe for the _instance changes as well 
</blockquote></details>

done

---

*[vaadin-context-menu.html, line 276 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60#-K_0hEHlQqQ36ALTCTKG:-K_3_jel3uuRoIOoXWv0:b-r18wir) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/a651d17a7e5ab0cdfa3205ab59757ba0bf5a2fcb/vaadin-context-menu.html#L276)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

This block should be removed since `_contextChanged` is run inside `open(e)` – which is the only place `opened` is set to true.
</blockquote></details>

done, thanks!

---

*[vaadin-context-menu.html, line 283 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60#-K_0ghJ2Ek92iFgv34RL:-K_3_mBWiKuPUZ8HP3GL:b1bf7ae) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/a651d17a7e5ab0cdfa3205ab59757ba0bf5a2fcb/vaadin-context-menu.html#L283)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Like @manolo pointed out, we should add `instance` argument to this observer as well so that we don't need to check for the `this.opened` status at all. Currently the check is needed because `_instance` is set only after the overlay has been opened for the first time.

Just making sure if you didn't know this already: when using observer functions in Polymer (1.x), the observers will be triggered only after all the properties are set to something else than `undefined`. So they can be effectively used to reduce `if` clauses for checking `undefined` properties.
</blockquote></details>

done, thanks for the explanation! Polymer is smarter than I thought!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60)*

**Comment by Saulis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/context.html, line 62 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60#-K_3fCJe8UUVcjmfLeqh:-K_3fCJe8UUVcjmfLeqi:bsajppx) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/e944a21b2a98fb7c79248f6bd24ca1a7fa9f5848/test/context.html#L62)):*
> ```HTML
>           });
> 
>           menu.async(function() {
> ```

Can this test be run without `async` now that we didn't add any new `async` calls?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60)*

**Comment by limonte** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/context.html, line 62 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60#-K_3fCJe8UUVcjmfLeqh:-K_3gfiigijTDWZUJn3M:b-duzahh) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/e944a21b2a98fb7c79248f6bd24ca1a7fa9f5848/test/context.html#L62)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Can this test be run without `async` now that we didn't add any new `async` calls?
</blockquote></details>

Yes! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60#-:-K_8NbUCq2HPmi5IPhu9:bnfp4nl)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/60#-:-K_8W1Gj0RCTeRACwRWr:bnfp4nl)*

**Pull request merged**
