### PR TITLE
Support --vaadin-overlay-viewport-bottom CSS property

### LINKED ISSUE #131: Landscape orientation navigation bar issue not fixed

### PR DESCRIPTION
**Pull request by platosha**
Fixes #131

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/132)

### CODE REVIEW

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/132#-:-L3SmgfDGOX-R-ua5rv4:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/132#-:-L3T3mzD_RsabbY1gZqb:bg7igkv)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/vaadin-context-menu.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/132#-L3TAzVXa_ebr2FpVeUo:-L3TAzVXa_ebr2FpVeUp:b-drtinn) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/3c5ca62e648278dcf2b432a431a57c541d276992/src/vaadin-context-menu.html#L31)):*
> ```HTML
>         bottom: 0 !important;
>         left: 0 !important;
>         padding: 24px;
> ```

BTW why did you remove this padding? It is still there in `vaadin-dropdown-menu` which has similar styles

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/132)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-context-menu.html, line 31 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/132#-L3TAzVXa_ebr2FpVeUo:-L3X2VcOMTVvA9-gg6Se:b-axizhd) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/3c5ca62e648278dcf2b432a431a57c541d276992/src/vaadin-context-menu.html#L31)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW why did you remove this padding? It is still there in `vaadin-dropdown-menu` which has similar styles
</blockquote></details>

This is leftover from default styles, that were removed previously.

It's not essential for the core element to have padding, therefore should not be included core styles, but rather defined in the theme.

Now that the Lumo theme overrides this anyway, this line is just an unnecessary overhead for the Lumo users.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/132)*

**Pull request merged**
