### PR TITLE
Replace no-close with close-on

### LINKED ISSUE #7: Change no-close to close-on
> Tomi Virkki @tomivirkki 12:12
How about then instead of "no-close" we could have a "closing-event", property (with default value of 'click').
Then one could set it to <... closing-event="change"> to make it work with <input type=date> or set it empty to have the "no-close" behaviour.

> Sauli Tähkäpää @Saulis 12:13
@tomivirkki best idea so far IMO
could it be called close-on so it would be an anagram of no-close ?

> Anton Platonov @platosha 12:16
`<vaaadin-context-menu open-on="grid-context-menu" close-on="click">...</vaadin-context-menu>`

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #7

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu/9)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/vaadin-context-menu-overview.adoc, line 41 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/9#-KRY0h-eichLKneKUKI3:-KRY0h-eichLKneKUKI4:bdxqx2l) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/eda872849d87a56394fcdb4a38c774a96030a05a/docs/vaadin-context-menu-overview.adoc#L41)):*
> ```AsciiDoc
> 
> By default, [vaadinelement]#vaadin-context-menu# closes when a [propertyname]#click# event is triggered inside the overlay.
> [propertyname]#closeOn# can be used to customize which event to listen for closing. When set to empty, no event is listened to.
> ```

It's not clear to me, maybe you can rephrase:

To replace  [propertyname]#click#  by any other event, use the [propertyname]#closeOn# property. You can set it to an empty value to avoid closing the overlay on click. 
Note that the user can always close the overlay clicking on any part of the UI out of the overlay, or pressing the escape key.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/9)*

**Comment by tehapo** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-context-menu.html, line 70 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/9#-KRY3Z0ERynMULj94CvP:-KRY3Z0ERynMULj94CvQ:b-fqluqg) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/eda872849d87a56394fcdb4a38c774a96030a05a/vaadin-context-menu.html#L70)):*
> ```HTML
> 
>         /**
>          * Event to listen for closing the context menu.
> ```

Maybe "Event _name_ to listen..." would be a bit more clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/9)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/overlay.html, line 98 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/9#-KRYA2BOUv7vX1Zb94gr:-KRYA2BOUv7vX1Zb94gs:b4znaaw) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/eda872849d87a56394fcdb4a38c774a96030a05a/test/overlay.html#L98)):*
> ```HTML
> 
>           it('should close on outside tap', function(done) {
> ```

Unnecessary empty line. Would make more sense to add a line between the event listeners though.

Btw, the order of the event listeners is unnatural for me. Would make more sense to setup the test conditions first (in the opened event), and then evaluate the outcome (in the closed event).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/9)*

**Comment by Saulis** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-context-menu.html, line 70 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/9#-KRY3Z0ERynMULj94CvP:-KRbnTxpqf8rBRm7Ti_I:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/eda872849d87a56394fcdb4a38c774a96030a05a/vaadin-context-menu.html#L70)):*
<details><summary><i>Previously, tehapo (Teemu Pöntelin) wrote…</i></summary>
> Maybe "Event _name_ to listen..." would be a bit more clear.
</details>
Done.

---

*[docs/vaadin-context-menu-overview.adoc, line 41 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/9#-KRY0h-eichLKneKUKI3:-KRbnVEhR5K9uUb4T5C8:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/eda872849d87a56394fcdb4a38c774a96030a05a/docs/vaadin-context-menu-overview.adoc#L41)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> It's not clear to me, maybe you can rephrase:
> 
> To replace  [propertyname]#click#  by any other event, use the [propertyname]#closeOn# property. You can set it to an empty value to avoid closing the overlay on click. 
> Note that the user can always close the overlay clicking on any part of the UI out of the overlay, or pressing the escape key.
</details>
Done.

---

*[test/overlay.html, line 98 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/9#-KRYA2BOUv7vX1Zb94gr:-KRbnWhEPOfGmiLZbnQn:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu/blob/eda872849d87a56394fcdb4a38c774a96030a05a/test/overlay.html#L98)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Unnecessary empty line. Would make more sense to add a line between the event listeners though.
> 
> Btw, the order of the event listeners is unnatural for me. Would make more sense to setup the test conditions first (in the opened event), and then evaluate the outcome (in the closed event).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/9)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/9#-:-KRc27iAVijuXRDVoAsU:bnfp4nl)*

**Comment by tehapo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-context-menu/9#-:-KRc5GxanoQQskXaXWui:bnfp4nl)*

**Pull request merged**
